### ISSUE TITLE
[mdoc] Support for F#, VB and C++ signatures

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#10]
Currently `mdoc` does not support F#, VB and C++ signatures for types. It would be helpful to have those, as soon we will enable automated documentation generation from ref sources.

**Comment by dend** [comment]
And to clarify here, by C++ syntax support, we mean C++/CLI.

**Comment by joelmartinez** [comment]
Per discussion via email, we would also like to add Powershell syntax support. 

We will probably break this GH issue up into multiple issues, one for each language. For Powershell, there is a project to use roslyn to convert C# to powershell:  
https://wandering.life/converting-c-powershell-using-roslyn/

This could serve as the basis for implementing a signature formatter.

**Comment by mpMelnikov** [comment]
- Regarding [https://wandering.life/converting-c-powershell-using-roslyn/](https://wandering.life/converting-c-powershell-using-roslyn/), we are not going to use Roslyn to convert C# to Powershell, and continue converting IL to Powershell, right? 
- Unfortunately, I can't see much source code in that article. However, we can use some info and ideas. It states that 

> "Aside from syntax such as Generics and Lambdas, PowerShell can convert easily to C#."

 Well, we don't need lambdas to generate TypeSignature and MemberSignature, but what about Generics? I can't find any approaches to declare generics class in Powershell (although since version 5.0 we have classes, also we can create generic classes [from other assemblies](https://stackoverflow.com/questions/11975130/generic-type-of-generic-type-in-powershell)). Should we skip generics types when we generate TypeSignature for PowerShell?

**Comment by joelmartinez** [comment]
@dend Is powershell in scope of [milestone #3](https://github.com/mono/api-doc-tools/milestone/3)?

Also, I'll point out that this is sort of an aggregate work item (referencing multiple languages) ... we have a specific entry for F#, but no one has created entries for VB and cpp.

**Comment by dend** [comment]
@joelmartinez no, PS is not part of the M3 work.

My suggestion is that we close this item and instead create separate ones for VB, C++ and JS. Specifically, because the work will be more nuanced as well. For example, we will have C++/Cx and WinRT-flavored C++.

**Comment by dend** [comment]
Closing in favor of #131, #132 and #133.
