### ISSUE TITLE
[mdoc] Support for F#-specific entities

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#108]
Before we get to the actual implementation details, would be great if @cartermp and @dsyme could outline the general F# language conventions that need to be accounted for during reflection.

**Comment by joelmartinez** [comment]
I'm really excited about improving support for F# in mdoc tooling, cause I <3 F# :) Just for tracking purposes, we have another issue, #10, which requests additional signatures. However, we will use this issue for the specific purposes of defining scope of work and requirements. 

Implementation note: we will need to write a new `MemberFormatter` class, and add it to the [other formatters](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/monodocer.cs#L157-L165). Additionally, we'll have to decide whether to add this by default, or put it behind a flag so users can opt-in. I'm _leaning_ towards adding it by default going forward .. but am open to discussion on the matter.

Looking forward to getting the details :)

**Comment by dsyme** [comment]
Hey @dend, @joelmartinez, here's an amail I sent to Den internally outlining some of the issues I saw:

The overall problem is that the generator is treating F# libraries as if they are just vanilla .NET/IL libraries for consumption from C#. This means we see the compiled form of F#-specific constructs. 
 That’s an OK starting point, but we really do need to modify the generator to present information in a way that’s suitable and appropriate for the F# programmer.   Specifically the doc generator should be modified to cope with a handful of F# specific constructs and names.  Once you do this everything will be much better   If the generator is open source we may be able to help with the changes.
 
* ``FSharpFunc<A,B>`` should be generated as the F# function type notation ``A -> B``.    Implement by looking for type name ``Microsoft.FSharp.Core.FSharpFunc`2``
 
* Basically every construct with an attribute [CompilationRepresenationAttribute](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/core.compilationrepresentationattribute-class-%5Bfsharp%5D) will likely need to be treated as somewhat special.  For example, curried functions should be detected and presented with the correct type signature. These have a [CompilationArgumentsCountAttribute](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/core.compilationargumentcountsattribute-class-%5bfsharp%5d) telling you the sequencing of curried arguments. Examples are List.map and Array.fold.
 
* Every construct with a [CompilationourceNameAttribute](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/core.compilationsourcenameattribute-class-%5bfsharp%5d) should be generated using the original F# source name (as given by the attribute).  For example, “List.map” not “List.Map”.
 
* Every class with the “Module” suffix should be generated using trimmed name (e.g. “Option” rather than “class OptionModule” etc.) and should use module terminology ("the Option module" not "static class Option")
 
* Because you are starting with .NET metadata, you are not seeing F# type abbreviations.  There is no way to access these abbreviations unfortunately except by decoding the F#-specific metadata in the DLL, which we don't want to do here. This means that in some specific cases you should hardwire a table giving the appropriate F# abbreviated type name for some FSharp.Core.dll and system types, especially 

  - ``option<T>” instead of “FSharpOption<T>``
  - ``list<T>`` instead of ``FSharpList<T>``
  - ``Choice<…>`` instead of ``FSharpChoice<…>``
  - ``ref<T>`` instead ``FSharpRef<T>``
  - ``seq<T>`` instead of ``IEnumerable<T>``
  - ``bool`` instead of ``Boolean``
  - ``uint16`` instead of ``ushort`` or ``UInt16``
  - ``int`` instead of ``int32``
  - Likewise other integer types
 
* When generating proper docs for F# modules, the appropriate F# terminology should be used.  Inside an F# module you have “values” and “functions” not “properties” and “methods”
 
* Discriminated unions like “FSharpChoice” are described as “classes” (and we are also revealing things that are really part of the compiled representation like the “Tags” class).  We should adjust the doc generator to use the F# reflection utilities in Microsoft.FSharp.Reflection to detect these discriminated union types and display them as such.
 
* The contents of “OperatorsModule” is particularly problematic and may need special treatment, compare with [this](https://review.docs.microsoft.com/en-us/fsharp-dotnet-api/api/microsoft.fsharp.core.operators?branch=master) and [this](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/core.operators-module-%5Bfsharp%5D) for example

**Comment by joelmartinez** [comment]
Thanks for the info @dsyme :) a few comments/questions:

- There are various other pieces in the pipeline involved in producing the docs: mdoc, 
  [Mono.Cecil](https://github.com/jbevain/cecil), [Ecma2Yaml](https://github.com/TianqiZhang/Ecma2Yaml), [DocFX](https://github.com/dotnet/docfx). I only mention this to set expectations that solutions for 
  some of the points you've raised will need to be implemented in various different places.
- "The overall problem is that the generator is treating F# libraries as if they are just vanilla .NET/IL libraries for consumption from C#. "
  - In the context of _mdoc_ specifically, part of this will remain true ... except that will change is that we'll generate F# signatures to go along with the other signatures we currently have (C#, IL, and DocId), and some other special case handling in order to encode as much information as necessary for future steps in the pipeline, in the xml.
  - Secondary question ... how can _mdoc_ identify an "F# library"? to go with the above point, _mdoc_ knows only that it's reading a .NET assembly. Should it treat any library with a reference to `FSharp.Core` as an F# lib?
- "Basically every construct with an attribute `CompilationRepresentationAttribute` will likely need to be treated as somewhat special"
  - Is there a definitive list of all of these constructs and how they should be treated? I want to make sure nothing falls through the cracks.
- F# Type Abbreviations
  - In the F# signature, we will definitely display [these types](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/fsharp-types) using the appropriate abbreviation ... we're already doing the same for primitive types in the C# signature. 
  - However, it definitely stands to reason that it would be helpful to include the abbreviations of these types in the various nodes that describe a type (`ReturnType`, `Parameter`, etc), which must be described using the FQN. I wonder if the library that we are documenting is identified as an "F# library" (per the question above) ... whether we should have an attribute, like `FSharpAbbreviation="Seq<T>"` on those nodes?
- F# Terminology
  - This is more of a front-end and editorial concern ... the front end should list headers for member groupings appropriately (the EcmaXML doesn't group properties, values, methods, other than listing a `MemberType` node, based on assembly metadata).
  - "We should adjust the doc generator to use the F# reflection utilities in Microsoft.FSharp.Reflection to detect these discriminated union types and display them as such."
    - Can you give me more information about this? A small sample in using that API to detect a discriminated union type would be awesome ... or otherwise, just a pointer to relevant documentation on using the API would suffice.
- "The contents of “OperatorsModule” is particularly problematic and may need special treatment"
  - Can you go into a bit more detail about exactly what you'd like to see here?
  - I can see that there is a `CompilationMapping` attribute on the type that shows it's a module, and then the page lists all of the modules that are contained therein
    - The display of that list is a front-end concern, so will probably have to be implemented in _Ecma2Yaml_ or _DocFx_ by seeing a type that has the above attribute, then querying the list of `Type` elements that are subtypes and also have the same attribute.

@Dend, see above for the few points that indicate something should probably be handled downstream.

**Comment by dsyme** [comment]
> how can mdoc identify an "F# library"? 

Super. Look for this attribute on a DLL or EXE:
```
  .custom instance void [FSharp.Core]Microsoft.FSharp.Core.FSharpInterfaceDataVersionAttribute...
```

> abbreviations.... whether we should have an attribute, like FSharpAbbreviation="Seq<T>" on those nodes?

Unfortunately we don't emit attributes indicating abbreviations, or any information about abbreviations.  There is a separate F# metadata blob (in its own format) that has this info, we could eventually include a reader for that.  For now I think it's ok to just hardwire the FSharp.Core abbreviations, since it's not common (or even encouraged) to use type abbreviations in other APIs


> Terminology... This is more of a front-end and editorial concern ... the front end should list headers for member groupings appropriately 

This may be work, because F# has both OO and module terminology, e.g.

```
module  M =
  let F x = 1 // function
  let a = 1 // value

type C() = 
  static member F x = x + 1 // static method
  static member a = 1 // static property
  member M x = x + 1 // instance method
  member b = 1 // instance property
```

Functions and values are compiled as static members and properties.  But they have simpler language rules (e.g. no overloading).

> Can you give me more information about this? A small sample in using that API to detect a discriminated union type would be awesome ... or otherwise, just a pointer to relevant documentation on using the API would suffice.

See [IsUnion](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/fsharptype.isunion-method-%5bfsharp%5d) and [GetUnionCases](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/fsharptype.getunioncases-method-%5Bfsharp%5D).  But note that I'm not sure we want ``mdoc`` or the other bits and pieces to have a dependency on ``FSharp.Core.dll``

> ... OperatorsModule... Can you go into a bit more detail about exactly what you'd like to see here?

It's the contents of the module that are the problem, e.g. the "overloaded addition operator".  An operator like ``a + b`` is defined in the F# library using a constrained generic method that uses F# specific notions of type constraints.  Effectively it's saying that ``a + b`` is valid if either the type of ``a`` or the type of ``b`` has a static method ``op_Addition``.   This is implemented via inlining and static resolution, though we also emit a fake "stub" method.

Like F# type abbreviations, none of this extra type constraint information is present in the compiled .NET signature for this "stub method".  This information is only accessible in the extra F# metadata blob.  

The old MSDN docs do a reasonable thing which is just show the generic signature but using preferred F# notation for the operator name. Any explanation about constraints is left to the special hand-written section on operators.

![image](https://user-images.githubusercontent.com/7204669/29284766-e151eaf4-8123-11e7-9abe-74cd1dd96ffc.png)

The new docs shows the wrong name (``Addition`` not ``op_Addition`` or ``(+)``):

![image](https://user-images.githubusercontent.com/7204669/29284814-12d64b56-8124-11e7-9897-52866557ed60.png)

and then in the linked section show ``op_Addition``.

**Comment by joelmartinez** [comment]
@dend, do we have the EcmaXml that is currently being generated for the F# libs somewhere accessible?

**Comment by dend** [comment]
@joelmartinez right here: https://github.com/dotnet/fsharp-api-docs/tree/master/dotnet/xml

Like we discussed earlier, in terms of prioritization, there are a number of other `mdoc` items that we'd want to make sure get resolved before we undertake the F# language support.

**Comment by mpMelnikov** [comment]
This discussion is fruitful and addresses many issues, so I'd like to clarify some general questions and suggest to create some separate issues relating to specific questions later.
1. When we generate MemberSignature node, we should consider MSDN documentation as a reference, right? For instance, according to this [MSDN page](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/list.append%5b't%5d-function-%5bfsharp%5d) we add 
```<TypeSignature Language="F#" Value="List.append : 'T list -> 'T list -> 'T list" />```
to the [xml here](https://github.com/dotnet/fsharp-api-docs/blob/master/dotnet/xml/Microsoft.FSharp.Collections/ListModule.xml#L67).
2. MSDN pages for F# contain not just the signature, but also the usage [example](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/list.append%5b't%5d-function-%5bfsharp%5d#syntax):
```
// Signature:
List.append : 'T list -> 'T list -> 'T list

// Usage:
List.append list1 list2
```
Do we generate it as TypeSignature too?
3. Correct me, if I'm wrong. According to this quote

> This may be work, because F# has both OO and module terminology, e.g.

we can generate at least 2 variants of code for the same IL code. How should we select the notation?
4. Will be the successful parsing of FSharp.Core.dll an indication that we dealt with this issue? Does it contain enough cases?
5. @joelmartinez in your opinion, will we need to use Microsoft.FSharp.Reflection? It seems to be the most challenging part of this issue because it can demand some global changes in the system, not just a new MemberFormatter.
6. I suppose we will need separate issues regarding:
- CompilationRepresenationAttribute
- OperatorsModule
- F# Type Abbreviations
- Some others, which I don't see right now.

**Comment by joelmartinez** [comment]
@mpMelnikov 

1. You should use MSDN as a guide for sure, however, the authoritative source should be the [F# language documentation](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/) ... that's what you should use as a primary reference when writing the signature formatter.
2. Usage in ecmaxml documentation is usually defined in remarks as code snippets ... so in that sense, no that seems to be outside of the scope of what _mdoc_ typically puts into the XML. However I'd like to have @dend's thoughts on this.
    - But yes, we will include `TypeSignature` in addition to `MemberSignature` for F#.
3. In context, this wasn't suggesting distinct signatures, it was talking about how F# has different concepts than what C# typically exposes. So as the example he gives, the concept of modules is compiled and expressed as static classes with static members in the resulting .dll.
4. This is going to take a little bit of research on your part, to be honest ... if at all possible, I want to avoid taking a dependency on any `*FSharp.*` assemblies; **if possible**. 
    - to use an example of how I think we _might_ be able to handle this, take a look at the [C# signature formatter](https://github.com/mono/api-doc-tools/blob/8822f7729c04ba22acbe9a9f1141d181ed725b6a/mdoc/Mono.Documentation/Updater/Formatters/CSharpFullMemberFormatter.cs#L302), and the way it handles operator overloads. By looking for specific patterns (in this case, the special method name), and outputting syntax accordingly.
    - My **hope** is that there will be enough clues in the mono.cecil definition types to let us detect when we should output a certain syntax (for example `seq` when we see an `IEnumerable` ... we do the same for C# type abbreviations [here](https://github.com/mono/api-doc-tools/blob/8822f7729c04ba22acbe9a9f1141d181ed725b6a/mdoc/Mono.Documentation/Updater/Formatters/CSharpFullMemberFormatter.cs#L30)).
5. see point above ... this will definitely be a challenge, and as I mentioned, will probably take some experimentation to see if we can get everything we need from cecil definitions, or just use smart defaults where possible.
6. I'm open to breaking up this task into multiple GH issues if you think it will make it easier to organize. Just create a new GH issue with a link to this one, let me know, and I'll add it to the milestone for you. Happy to discuss

**Comment by dend** [comment]
@joelmartinez @mpMelnikov ideally, we also generate the usage signature. I believe we can put some heuristics to use here, and if something is not clear, we can always refer to the F# team to understand how we can infer usage based on type data.

**Comment by joelmartinez** [comment]
Hmm, ok ... then what we can do is add another optional attribute to the `MemberSignature` and `TypeSignature` elements: `Usage`. 

@mpMelnikov this usage signature would ideally be implemented as a _separate_ formatter (makes it easier to unit test individually). And I think we can probably add an overridable member to the base formatter class which returns the usage formatter. The default implementation would simply return null, and the F# formatter would return the F# usage formatter. With that in place, the code that generates the actual XML would check the formatter to see if the `.UsageFormatter` is null, and if not set the `Usage` attribute :)

**Comment by mpMelnikov** [comment]
@joelmartinez I like this idea. Thank you for the detailed information.

**Comment by joelmartinez** [comment]
another requirement that I mentioned in [another comment](https://github.com/mono/api-doc-tools/issues/132#issuecomment-337608829). 

> Additionally, I should mention one more requirement that we probably haven't discussed in these various language/signature items ... the only default signature formatters are ILASM and C#. We have already added `docid`, which can be triggered by passing [`--use-docid`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L198) on the CLI. I would like to generalize this so that we can use a new CLI parameter called `-lang F#`, `-lang C++/CLI`, etc, to add the additional signature formatters. For backwards compatibility, `--use-docid` should still work (probably just call the same function as the new `-lang` parameter with `docid` as the argument).

**Comment by mpMelnikov** [comment]
@joelmartinez 
I have quite an important question.
Now F# signatures in MSDN look like [this](https://msdn.microsoft.com/visualfsharpdocs/conceptual/var.global-method-%5bfsharp%5d):
```
static member Global : string * Type -> Var
```
It's not exactly what was in the source code, but it seems to be a [signature](https://fsharpforfunandprofit.com/posts/function-signatures/). The analogy is quite inaccurate, but it's like declaring C# delegate instead of C# method declaration.
The real source code looks like [this](https://github.com/fsharp/fsharp/blob/51aaa012e73fefba5756a57537e3dd3f0a2ec9c8/src/fsharp/FSharp.Core/quotations.fs#L108):
```
static member Global(name,typ: Type) = 
```
What is an expected way to generate signatures?

**Comment by joelmartinez** [comment]
That's a good question ... the F#-specific signature that you link to (and seemingly what MSDN is using) is more of a _description_ of what the function/member looks like. _mdoc_ signatures generally describe the syntax used to declare that member/type, so it's a good thing you're asking.

I _suspect_ that the F# community will want the F# specific signatures, because they are used to dealing with that syntax in documentation. Additionally, in many cases due to type inference, an idiomatic F# codebase may not even use type annotations and other things (as in the example you gave ... `name` is inferred to be a string). 

Would love if we had some additional commentary on this from @dsyme, @lobrien, @dend, and @conceptdev. Thoughts?

**Comment by cartermp** [comment]
The type signature is definitely the preferred way to do things.  They are displayed like that in the following places:

* QuickInfo in tooling (VS, VSCode, VS4mac, Rider)
* F# Interactive
* Existing MSDN documentation
* Other online learning resources, like the F# Wiki

This is also consistent with other functional programming languages, where the type signature is what is displayed for functions and types.

**Comment by mpMelnikov** [comment]
@joelmartinez 
There is an issue with F# constraints representation. Part of constraints doesn't have any representation in IL code:
```
// Member constraint with static member
type Class4<'T when 'T : (static member staticMethod1 : unit -> 'T) > =
    class end

.class nested public auto ansi serializable beforefieldinit Class4`1<T>
	extends [mscorlib]System.Object
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 03 00 00 00 00 00
	)
}
```
```
// Member constraint with instance member
type Class5<'T when 'T : (member Method1 : 'T -> int)> =
    class end

.class nested public auto ansi serializable beforefieldinit Class5`1<T>
	extends [mscorlib]System.Object
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 03 00 00 00 00 00
	)
}
```
```
// Member constraint with property
type Class6<'T when 'T : (member Property1 : int)> =
    class end

.class nested public auto ansi serializable beforefieldinit Class6`1<T>
	extends [mscorlib]System.Object
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 03 00 00 00 00 00
	)
} // end of class Class6`1

```
```
// Reference type constraint
type Class8<'T when 'T : not struct> =
    class end

.class nested public auto ansi serializable beforefieldinit Class8`1<class T>
	extends [mscorlib]System.Object
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 03 00 00 00 00 00
	)
}
```
In the last example, we have the same IL code for `when T : null` constraint.
```
// Enumeration constraint with underlying value specified
type Class9<'T when 'T : enum<uint32>> =
    class end

.class nested public auto ansi serializable beforefieldinit Class9`1<T>
	extends [mscorlib]System.Object
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 03 00 00 00 00 00
	)
} 
```
```
// 'T must implement IComparable, or be an array type with comparable
// elements, or be System.IntPtr or System.UIntPtr. Also, 'T must not have
// the NoComparison attribute.
type Class10<'T when 'T : comparison> =
    class end

.class nested public auto ansi serializable beforefieldinit Class10`1<T>
	extends [mscorlib]System.Object
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 03 00 00 00 00 00
	)
}
```
```
// 'T must support equality. This is true for any type that does not
// have the NoEquality attribute.
type Class11<'T when 'T : equality> =
    class end

.class nested public auto ansi serializable beforefieldinit Class11`1<T>
	extends [mscorlib]System.Object
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 03 00 00 00 00 00
	)
}
```
```
type Class12<'T when 'T : delegate<obj * System.EventArgs, unit>> =
    class end

.class nested public auto ansi serializable beforefieldinit Class12`1<T>
	extends [mscorlib]System.Object
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 03 00 00 00 00 00
	)
}
```
```
.class nested public auto ansi serializable beforefieldinit Class13`1<T>
	extends [mscorlib]System.Object
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 03 00 00 00 00 00
	)
} 
```
```
.class nested public auto ansi serializable beforefieldinit Class14`2<T, U>
	extends [mscorlib]System.Object
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 03 00 00 00 00 00
	)
} 
```

I've even tried to use Microsoft.FSharp.Reflection, but without success.

**Comment by joelmartinez** [comment]
@mpMelnikov The first thing that I'd like to ask, is for you to check and see what happens when you define one of these constraint types, and then consume them from C# with a type that doesn't conform to the constraint. Is there a compile-time error, or does an error occur at runtime?

Unfortunately, if it's not in the IL, there's nothing that we'll be able to do currently in mdoc, since we work from compiled assemblies. Another feature that (AFAIK) is not represented in the IL is [units of measure](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/units-of-measure).

**Comment by dend** [comment]
@KevinRansom @cartermp to comment here as well, since this will impact how the documentation will be rendered.

**Comment by mpMelnikov** [comment]
@joelmartinez 

1. > consume them from C# with a type that doesn't conform to the constraint

Thank you for the idea! I've tried it, and they just work. No compilation error and even runtime error is fired only when we try to use some specific function which was declared in the constraint (`TestFSharpConstraints` unit test). So, how should we deal with these constraints?

2. > Another feature that (AFAIK) is not represented in the IL is units of measure.

Yes, you're right, I can't see signs of units of measure in IL code. 
```
// F#
let xvec : vector3D<m> = { x = 0.0<m>; y = 0.0<m>; z = 0.0<m> }
let v1vec : vector3D<m/s> = { x = 1.0<m/s>; y = -1.0<m/s>; z = 0.0<m/s> }
```
```
// IL
.property class UnitsOfMeasure/vector3D xvec()
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 09 00 00 00 00 00
	)
	.get class UnitsOfMeasure/vector3D UnitsOfMeasure::get_xvec()
}

.method public specialname static 
	class UnitsOfMeasure/vector3D get_xvec () cil managed 
{
	// Method begins at RVA 0x2248
	// Code size 6 (0x6)
	.maxstack 8

	IL_0000: ldsfld class UnitsOfMeasure/vector3D '<StartupCode$mdoc-Test-FSharp>.$UnitsOfMeasure'::xvec@75
	IL_0005: ret
} // end of method UnitsOfMeasure::get_xvec

.property class UnitsOfMeasure/vector3D v1vec()
{
	.custom instance void [FSharp.Core]Microsoft.FSharp.Core.CompilationMappingAttribute::.ctor(valuetype [FSharp.Core]Microsoft.FSharp.Core.SourceConstructFlags) = (
		01 00 09 00 00 00 00 00
	)
	.get class UnitsOfMeasure/vector3D UnitsOfMeasure::get_v1vec()
}

.method public specialname static 
	class UnitsOfMeasure/vector3D get_v1vec () cil managed 
{
	// Method begins at RVA 0x2250
	// Code size 6 (0x6)
	.maxstack 8

	IL_0000: ldsfld class UnitsOfMeasure/vector3D '<StartupCode$mdoc-Test-FSharp>.$UnitsOfMeasure'::v1vec@77
	IL_0005: ret
} // end of method UnitsOfMeasure::get_v1vec

```

3. A similar issue is "inline" keyword, which is resolved by the compiler. But, as I can see, VS QuickInfo don't show this info either.
![image](https://user-images.githubusercontent.com/7716624/32700182-a5605e54-c7d2-11e7-9008-a8fa768c0d08.png)

4. While implementing F# formatter, I took into account this discussion and MSDN examples. [That's why](https://msdn.microsoft.com/visualfsharpdocs/conceptual/control.mailboxprocessor%5b%27msg%5d-class-%5bfsharp%5d) I've added all members to type signatures. But as we discussed on Friday, not all we see in MSDN is generated in mdoc, now I'm not sure whether mdoc should generate such signatures. So, how should it look like in mdoc?

5. When there is CompilationRepresenationAttribute, we don't have any information in IL code about F# real method name. So, we replace the first symbol with the lower case, for F# Core Library this approach works, but I'm not sure it's a correct approach.

6. As it was mentioned [here](https://github.com/mono/api-doc-tools/issues/133#issuecomment-343589924), we abandoned the idea of a separate FSharpUsageFormatter. How should I implement usage signatures for F#?

7. I've pushed last changes here #146 . I would really appreciate if you could take a look at it. FSharpFormatter functionality can be investigated with `FSharpFormatterTests` class.

**Comment by mpMelnikov** [comment]
8. Another issue is "[statically resolved type parameters](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/generics/statically-resolved-type-parameters)"  that is replaced with an actual type at compile time . For example, in [MSDN](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/array.averageby%5b't,%5eu%5d-function-%5bfsharp%5d) we see:
```
Array.averageBy : ('T -> ^U) -> 'T [] -> ^U
```
In mdoc the following signature is generated:
```
Array.averageBy<'T,'TResult> : ('T -> 'Result) -> 'T[] -> 'Result
```
It seems, there aren't any clues in IL code:
```
.method public static 
	!!TResult AverageBy<T, TResult> (
		class Microsoft.FSharp.Core.FSharpFunc`2<!!T, !!TResult> projection,
		!!T[] 'array'
	) cil managed 
{
	.custom instance void Microsoft.FSharp.Core.CompilationArgumentCountsAttribute::.ctor(int32[]) = (
		01 00 02 00 00 00 01 00 00 00 01 00 00 00 00 00
	)
	.custom instance void Microsoft.FSharp.Core.CompilationSourceNameAttribute::.ctor(string) = (
		01 00 09 61 76 65 72 61 67 65 42 79 00 00
	)
```

**Comment by dend** [comment]
Also tagging @dsyme who can potentially help.

**Comment by joelmartinez** [comment]
@mpMelnikov "... abandoned the idea of a separate _FSharpUsageFormatter_"

My comment there was:

> F# has also initially requested usage samples, but for now that has been pushed off (afaik)

So it's not that we've abandoned it, it's that I thought (seemingly erroneously) we deemed them to be out of scope for this milestone. If we require usage signatures, then we need to have a discussion about introducing the concept of a usage formatter, and the implications therein.

I'm still thinking about the other questions/items you've brought up ... will respond soon :)

**Comment by mpMelnikov** [comment]
> So it's not that we've abandoned it, it's that I thought (seemingly erroneously) we deemed them to be out of scope for this milestone. 

It's a good question. The last message about usage samples was:

>ideally, we also generate the usage signature. I believe we can put some heuristics to use here, and if something is not clear, we can always refer to the F# team to understand how we can infer usage based on type data.

@dend could you clarify, please, is it out of scope for this milestone?

**Comment by joelmartinez** [comment]
*if* they are in scope, then my proposal for how we should implement usage formatters is as such:

1. Add a `public virtual MemberFormatter UsageFormatter {get; protected set;}` property (null by default) to the `MemberFormatter` class.
2. Any existing language formatter can assign a formatter to it, that when called, would produce the usage for any type or member, appropriate to that language.
3. When adding `TypeSignature` or `MemberSignature` entries, we can simply check `if (formatter.UsageFormater != null)`, and then add the result to the `Usage` attribute.

**Comment by joelmartinez** [comment]
Going back to the questions I hadn't yet addressed from your [previous question](https://github.com/mono/api-doc-tools/issues/108#issuecomment-343744584) ... I suspect that for these features that are present _only in the source code_, we will simply have to accept that they will not be present in the signatures as is. As you mentioned, even in the case of things like `inline`, they are not shown by visual studio's debugger/intellisense, and there are some F# specific constraints that are not supported after compilation from other languages.

So, as it stands today, _mdoc_ takes an assembly, and presents it *as is* ... as it would be consumed by any other .net language. If there are language features that require access to the source code, that would take another level of parsing the source code in order to present the signatures _as written_ in the source code.

@dend ... do you have any information on how the API docs were produced for MSDN? If we're going to need to have the corresponding source code for fully fleshed out signatures, then I recommend that this be broken out into another task, as it's quite an escalation of effort.

--------

> While implementing F# formatter, I took into account this discussion and MSDN examples. That's why I've added all members to type signatures. But as we discussed on Friday, not all we see in MSDN is generated in mdoc, now I'm not sure whether mdoc should generate such signatures. So, how should it look like in mdoc?

@mpMelnikov On this point, I would say that no, I would prefer that the _mdoc_ signature contain only the type-level information. I'm prepared to concede on this point if the stakeholders (ie. @dsyme ) think otherwise ... but until then :)

**Comment by dsyme** [comment]
@joelmartinez @dend @cartermp  I wasn't following this thread, sorry.  Could someone summarize where we are at with F# signature formatting, and what remaining known issues exist?  Thanks

**Comment by cartermp** [comment]
It looks like there was a lot of progress by @mpMelnikov in #146, with a few issues: showing generic constraints seems to be an issue we can't do in the short-term, for example.

@joelmartinez @dend Is there a way to see this work in a staging environment so that it's easier to evaluate the remaining issues?  It sounds like the majority of problems were tackled in #146, but it'll be good to give it another look.

**Comment by dend** [comment]
@cartermp @dsyme not yet, we are still working on fixing the `mdoc` tool before we make the changes go to docs.microsoft.com - once the changes are live, we will be able to stage some additional content.

To re-iterate something that was discussed by @joelmartinez and @mpMelnikov, there are a few things that are currently not supported:

* Units of measure
* Some constraints
* The `inline` keyword, since it's resolved at compile-time

**Comment by dsyme** [comment]
@dend @cartermp Thanks!
