### ISSUE TITLE
[mdoc] Support extra elements in the generated ECMAXML

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#12]
Based on the documentation work being done, we'd like to add a number of extra elements to the generated ECMAXML:

* `<examples>` - a node that will contain multiple child `<example>` nodes, or a CDATA-wrapped Markdown representation of example content.
* `<altobsolete>` - an element that allows a type that is an alternative to the current obsolete type.
* `<isinternal>` - determines whether the API in question is internal or not.

**Comment by jonpryor** [comment]
> we'd like to add a number of extra elements to the generated ECMAXML:

...to the *generated* ECMA XML? I am not sure how to interpret this statement. `mdoc update` *generates* "stub" XML, and can even attempt to emit `<exception/>` elements (via [`mdoc update --exceptions[=SOURCE]`](http://docs.go-mono.com/?link=man%3amdoc(1)), but in no case will `mdoc update` generate `<example/>`.

> * `<examples/>`

Why is it necessary to have a node to contain `<example/>`, instead of [just having multiple `<example/>` elements](https://github.com/mono/mono/blob/master/mcs/class/Mono.Options/Documentation/en/Mono.Options/OptionSet.xml#L300-L827)? ([Rendered example](http://docs.go-mono.com/?link=T%3aMono.Options.OptionSet); note that there are *3* `<h2/>` **Example**s.)

I suppose it might be useful to have some text between the `<example/>` elements, but even that cursory thought doesn't *really* make sense, as the `<example/>` can contain a `<para/>` to explain the example. Additionally, multiple `<example/>` elements are rendered in-order; you can thus control the pre-`<code/>` and post-`<code/>` text that is displayed within each example.

> * `<altobsolete/>`

Interesting idea, though I'm not sure I immediately see how it's superior to `<altmember/>` or `<seealso/>`.

...especially considering that, in all likelihood, you'd be updating the `<remarks/>` to mention the new type to use anyway (`"This type is obsolete. Please use the <see cref="..." /> type."`). How many different ways do we need to mention types?

As a counter-argument, `<altobsolete/>` *might* be useful in getting a count from doc-tools for how many obsolete members there are...maybe...but I'm not certain *why* that would be desirable, or how that would be better than the current `[Obsolete (...)]` which is emitted in the C# signatures.

> * `<isinternal/>`

This is where we might have a difference of opinion, or I lack imagination. To wit: documentation is for *public* consumers, IMHO. This is why [`mdoc update` *ignores* `private` and `internal` members](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/monodocer.cs#L2759) (^1), *not* emitting them into the generated XML. `<isinternal/>` thus doesn't really make sense; how is this internal member getting into the XML in the first place?

---

(^1): [`MemberFormatter.GetDeclaration()`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/monodocer.cs#L4351) returns `null` -- causing the member to be skipped -- when:

1. A Type hits `MemberFormatter.GetTypeDeclaration()`, which is overridden in e.g. [`CSharpFullMemberFormatter.GetTypeDeclaration()`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/monodocer.cs#L5109) and returns `null` when [`GetTypeVisibility()`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/monodocer.cs#L4661-L4675) finds a non-public, non-protected type.

2. Methods hit [`MemberFormatter.GetMethodDeclaration()`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/monodocer.cs#L4407-L4408), which returns `null` if no visibility is found, and `MethodFormatter.AppendVisibility()` only checks for `public` and `internal`.

3. etc...

**Comment by dend** [comment]
@jonpryor thanks for the feedback!

## Examples

If I interpret correctly what you are saying, I can just dump multiple `<example>` nodes directly in the `<Docs>` node? I am OK with that, just want to make sure it's allowed in the XML.

## Alternative to obsolete types

From a logistical perspective, we can put that anywhere, really. So if the user would edit remarks, that would be OK. However, we are working out an automatic process for the publishing system to pick up the maximum amount of information in a structured way, so that we won't have to guess how a certain writer decided to delineate obsolete alternatives in their article.

Regarding `<altmember>`, I was under the impression that will render the *See Also* section - can we leverage it simply as an *alternative member to this*?

## IsInternal

There are some APIs that are in the public docs but are designed to be used by the original vendor only. This can also be helpful for APIs that were accidentally released publicly, but we can't un-release them because that would be a breaking change.

Here are some examples:
* [IdIterator Structure](https://msdn.microsoft.com/en-us/library/system.xml.xsl.runtime.iditerator(v=vs.110).aspx)
* [ProcessDesigner.PreFilterProperties Method (IDictionary)](https://msdn.microsoft.com/en-us/library/system.diagnostics.design.processdesigner.prefilterproperties(v=vs.110).aspx)

Notice that these have the following intro paragraph:

> This API supports the product infrastructure and is not intended to be used directly from your code.

**Comment by jonpryor** [comment]
> However, we are working out an automatic process for the publishing system to pick up the maximum amount of information in a structured way

How does it do that? Nothing requires that the `[Obsolete]` message actually mention a type or member, or what format such a reference would take, so I'm not entirely sure you can *automatically* take `[Obsolete]` attributes and emit documentation XML without human intervention. If you can, *great*, I'd just like to know how that works. :-)

> Regarding `<altmember>`, I was under the impression that will render the *See Also* section

That is correct, and having "obsoleting" types and members -- types and members which should be used *instead of* the obsolete types and members -- listed within the *See Also* section makes lots of sense to me. I don't see this as being a problem.

> can we leverage it simply as an *alternative member to this*?

I'm sorry, I don't quite understand what you're asking. :-(

# IsInternal

Perhaps `<shouldHaveBeenInternal/>` would be a more descriptive element? :-)

That said, I'm still not sure I understand how this would work, big-picture-wise.

So let me take a step back: *much* of the content of the `<Docs/>` element is rendered "as is", but with "formatting" applied. For example, `<see/>` is rendered as a link ("formatting"), `<para/>` is rendered as paragraphs ("formatting"), `<c/>` is rendered in a fixed-width font ("formatting"), etc.

This is fairly straightforward to understand.

However, that's not *all* of the elements. Some elements aren't *just* formatting; they're also *content*. The `<example/>` element emits an **Example** header. The `<altmember/>` elements are placed into a separate *See Also* section. `<param/>` is likewise rendered into a separate *Parameters* section, and `<exception/>` is placed into an **Exceptions** table.

Then we get the *really* confusing content-emitting elements, `<block/>`. `<block type="behaviors"/>` creates an **Operation** "section". `<block type="overrides"/>` creates a **Note to Inheritors** section.

Personally, I find these "elements which emit content" to be *really* confusing. I *always* need to read [the documentation](http://docs.go-mono.com/?link=man%3amdoc(5)) to remember what those different `//block/@type` values *are*, and what content they *emit*.

Which brings us back to a possible `<isinternal/>`/`<shouldHaveBeenInternal/>` element which emits content: it's Yet Another Element that isn't immediately obvious (to me!) about how it will be rendered. It's not "just formatting", it's *content*.

That can be a good thing. That can also be an *annoying* thing. I'm not sure where the proper balance should be, lest we turn into a sea of LaTex macros, all alike, impenetrable to anyone who hasn't been using it for years.

**Comment by dend** [comment]
@jonpryor regarding obsolete types, we just want to show an alternative to the type that is not obsolete. Currently, that information is embedded in the attribute itself, e.g. `[System.Obsolete("use class B")]` - but granted, that might not have a fully qualified name. I am fine using `<altmember>` that will go under *See Also*. Just wanted to clarify that it's not something that is implemented in some other way.

Regarding `<isInternal>`, you are correct - it is content. It should just be a plain string that states exactly as my previous comment. Hopefully in itself it's not a big change or clutter to the ECMAXML file 😄 It will only  be added manually for a limited set of APIs.

**Comment by jonpryor** [comment]
I still don't like `<isinternal/>` as a name, as it just doesn't "read" right to me -- "this public member `Foo` is internal?!"

I'd prefer a name that doesn't make me second guess things, like `<isframework/>` (maybe?) or `<forInternalUseOnly/>` or `<notForPublicConsumption/>`. *Something* that, when read in-context, doesn't sound like it's contradicting that context.

**Comment by dend** [comment]
@jonpryor reasonable. `<forInternalUseOnly>` sounds good.

**Comment by joelmartinez** [comment]
Ok, so to summarize, the outcome after discussion is that you are just looking to have one additional tag added:

- `<forInternalUseOnly />` - will be a marker, to be left alone by `mdoc update`.

The other two: `examples`, and `altmember` are no longer necessary as additions, because you learned that you can add `example` nodes in the documentation; and `altmember` will be used in lieu of the requested `altobsolete`.

Am I understanding the outcome correctly? :D

**Comment by jonpryor** [comment]
`mdoc update` will already ignore `<forInternalUseOnly` -- and any other arbitrary XML within the `<Docs/>` section.

What "needs" to happen is twofold:

1. Update [`monodoc-ecma.xsd`](https://github.com/mono/api-doc-tools/blob/master/mdoc/Resources/monodoc-ecma.xsd) so that it's considered a valid element, so that `mdoc validate` won't flag an error.
2. (Optional?) Update `monodoc.dll` ([`ecmaspec-html.xsl`](https://github.com/mono/api-doc-tools/blob/master/monodoc/Resources/ecmaspec-html.xsl)?) to match `forInternalUseOnly` and emit the appropriate message.

**Comment by dend** [comment]
Sounds good, thanks @jonpryor and @joelmartinez

**Comment by joelmartinez** [comment]
Just to leave an explicit note here in this issue ... I've added the element to the XSD, so it will validate correctly. However, the 2nd ("optional") half of @jonpryor's suggestion I've broken out into a separate issue that we can add in later: #24 :)
