### ISSUE TITLE
[mdoc] Support different platform variants and versions

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#13]
`mdoc` does a good job detecting assembly versions, but those are not always representative of the platform variant and the platform version itself. So, say, .NET Framework 4.0 and 4.5 will both have `mscorlib.dll` at version 4.0 - we need to be able to specify the variant and version during `mdoc` run.

As an example of the proposal:

```
mdoc update *.dll -o TestFolder --platform netfx --platformversion 4.0
```

**Comment by jonpryor** [comment]
Variations on this have been a longstanding "problem"/"desired feature", the primary problem being one of representation. For example, "Desktop .NET", Xamarin.Android, Xamarin.iOS, and Xamarin.Mac all support `System.String.Length`, and three of those have the same assembly versions (v2.0.5.0)! It could be extremely handy to have a single set of "core documentation" shared by *everything*, and the documentation saying "This member is supported in platforms: .NET, Android, iOS, Mac".

Unfortunately, the current `<AssemblyInfo/>`/`<AssemblyVersion/>` blob doesn't really support that at all. Some alternate construct is required.

Additionally, I'm not entirely certain that we want to save that info as per-member data, as it would require that all docs be updated whenever a new platform is introduced.

**Comment by dend** [comment]
@jonpryor this ask is specifically related to an automated process that will generate documentation from pre-defined platform drops. I agree that this goes slightly beyond `<AssemplyInfo>` and potentially needs another node along the lines of:

```
<PlatformInfo>
     <PlatformVersion Variant="netfx" Version="4.0" />
     <PlatformVersion Variant="netfx" Version="4.5" />
     <PlatformVersion Variant="netfx" Version="3.5" />
     <PlatformVersion Variant="netfx" Version="2.0" />
     <PlatformVersion Variant="xamarinbcl" Version="1.0" />
</PlatformInfo>
```

**Comment by joelmartinez** [comment]
Yes indeed ... the current proposal to address this need is as follows:

-----

The idea is to be able to have a single source of information for all .NET APIs, regardless of the subset that is exposed.

Consider `System.Type` which is part of mscorlib.dll since 1.0, but has evolved by adding more members.   Or consider new data types that have been added in new versions of the frameworks.

What we want is to be able to generate an XML document for each type that annotates in which version the type and members are present.

For example, imagine the type "Foo", in version 1 it only had a constructor, but in version 2, it added the member Bar, we would like the Foo.xml file to contain the documentation for Foo, Foo::ctor, Foo.Bar, and annotate with attributes that Foo exists in ".NET 1.0, .NET 2.0, .NET 4.5, .NET Standard 1.5", the assemblies where it exists are "mscorlib.dll" for all, but for .NET Standard, it lives in "System.Runtime.dll".

The tool could operate on a directory where all the assemblies are listed, like this:

     .NET 1.0/
          mscorlib.dll
          System.dll
          ..
     .NET 2.0/
          mscorlib.dll
          System.dll
          ..
    .NET Standard 1.6/
          System.Runtime.dll
          Foo.dll
          ..

And update a collection of reference docs, to contain the information, something like:

    <Type Name="Foo">
        <Available>
           <Framework Name=".NET 1.0"/>
           <Framework Name=".NET 2.0"/>
           <Framework Name=".NET Standard 1.6"/>
        </Available>
        <Member Name="Bar">
            <Available>
               <Framework Name=".NET 2.0"/>
               <Framework Name=".NET Standard 1.6"/>
            </Available>

**Comment by dend** [comment]
@joelmartinez like the proposal, would just suggest separating the framework identifier and version into two different attributes.

**Comment by joelmartinez** [comment]
@dend Can the "variant" and "version" be encoded in the directory folder? so taking `corefx-1.0` and splitting by `-`?

I think that, aside from that and a few other specifics which we can definitely compromise on, this proposal can address your needs ... the only minor difference from what you posted in the first description is that all of the assemblies would have to be processed at once, rather than processing individually for `netfx-1.0`, `netcore-1.0`, etc.

So for example, the command line invocation could look something like:

```
mdoc update path/to/folderOfFolders -o en -batch
```

the use of `-batch` (really could be anything) is just a flag to tell mdoc to process the folders ... and then the folders in `path/to/folderOfFolders` would simply contain everything that we want to include in this one doc set.

**Comment by dend** [comment]
@joelmartinez yeah I think that would absolutely be reasonable since we control the drop locations.

**Comment by joelmartinez** [comment]
Next thing on the agenda then is to agree on specifics, first of which means [naming](https://martinfowler.com/bliki/TwoHardThings.html)! 

So far we've seen two options for the names of the XML nodes that will hold this information:

- `<Available><Framework Name="netfx" Version="1.0" /></Available>`
- `<PlatformInfo><PlatformVersion Variant="netfx" Version="4.0" /></PlatformInfo>`

Also, the parameter to trigger this functionality ... `-batch` ... any other preferred suggestions?

And lastly, just a few questions on how the feature should work. 

- How do we want to treat pre-release documentation in this model? Will we simply drop a folder for the pre-release assemblies (`netfx-7.9RC`)?
- If the answer to the 2nd part of the question above is yes, should we simply remove any name/variant that isn't included in the directory?

@jonpryor/@dend ... your thoughts would be appreciated :)

**Comment by dend** [comment]
@joelmartinez @jonpryor 

Regarding the nodes, the only reason I went with `PlatformInfo` is to be consistent with `AssemblyInfo`. 

On parameter naming, I think `--batch` sounds good, given that it will process multiple folders.

And last but not least, on questions posted:

1. Yes, we would simply follow the convention for naming for anything that is pre-release.
2. If we re-run the tool on the same batch and a variant is gone, I believe we should also remove it from the XML files.

**Comment by jonpryor** [comment]
Regarding naming and [the proposal](https://github.com/mono/api-doc-tools/issues/13#issuecomment-273597744), I don't think that we need to follow `AssemblyInfo` as an example, because the relevant information will be stored in a completely different set of files, not within the per-class documentation files. As such, I like the proposed names of `<Available/>` and `<Framework/>`.

I *don't* like the `-batch` option name, as it doesn't intuitively mean anything to me. I would instead suggest a `-frameworks PATH` option:

    mdoc update -o en -frameworks path/to/frameworks

Where `path/to/frameworks` would be assemblies-within-framework-directories:

    frameworks/
        netfx-1.0
            mscorlib.dll
            ...
        Xamarin.Android 7.0
            mscorlib.dll
            ...
        ...

This also means that where `mdoc update` currently expects *files*, we don't need to update the code and documentation to also expect directories, which affords a degree of increased error reporting. If `mdoc update -frameworks FILENAME` is used, we can report a meaningful error that a *directory* is required for `-frameworks`, not a filename, etc.

**Comment by joelmartinez** [comment]
@jonpryor really good feedback, thanks. 

> ... because the relevant information will be stored in a completely different set of files, not within the per-class documentation files

Can you expand on this? I was operating on the assumption that this information *would* be stored at the type and member level, in the per-class XML files. Do you think it would be better if we had a separate set of XML files to store the availability information?

**Comment by jonpryor** [comment]
(Aside: I *really* wish I could find the emails that I'd *swear* had some of these thoughts...)

@joelmartinez wrote:

> I was operating on the assumption that this information *would* be stored at the type and member level

I believe the "frameworks which support this member" information should *not* be stored with the documentation for that member, because it doesn't "scale". Assume for the moment that we have 6 frameworks that we want to support: .NET 4.5, CoreFX, .NET Standard, Xamarin.Android, Xamarin.iOS, Xamarin.Mac.

...except there aren't 5; those 5 are *unversioned*. What we'd *actually* need is specific versions for each of those:

* .NET 4.5, .NET 4.6, .NET 4.6.2 (?), ...
* CoreFX 1.0, CoreFX 2.0, ...
* .NET Standard 1.1, .NET Standard 2.0, ...
* Xamarin.Android 6.0, 6.1, 7.0, 7.1, ...
* Xamarin.iOS 9, 10, ...
* Xamarin.Mac 1, 2, 3...

There are *thousands* of files; [`mscorlib.dll` currently contains documentation for *1527* types](https://github.com/mono/mono/tree/master/mcs/class/corlib/Documentation/en).

If we store framework version information "inline" with each of those types, that means *every time* we add a new framework, *ever one* of those files needs to be updated. What's more, that framework information needs to be updated for each type *and member*.

Consider [the documentation for `System.Type`](https://github.com/mono/mono/blob/master/mcs/class/corlib/Documentation/en/System/Type.xml), which contains 180 members. Assume further we're adding a new framework:

    <Framework Name="Xamarin.Android" Version="7.1" />

With indentation (the wrong indentation? but whatever...), that's 60 *bytes*, *per member* or ~10KB to add a single framework to `Type.xml`. There are ~1398 members in `mscorlib.dll`, or ~84KB to store that information.

For *one* framework, individually.

Never mind all the extra added "noise" when editing those XML files. Yes, it's easy to ignore them, but many editors have problems with large files. `Type.xml` is already 11000+ lines; adding 180 lines for *every supported framework* is going to be a significant number of added lines...

This is why I was thinking that framework information could be kept in a separate "location."

I'm less certain about what this location could or should be. It could be a SQLite DB; it could be a separate mass of XML files.

Regardless, what keeping framework information separate from the documentation permits is adding new supported frameworks and framework versions without "disturbing" the documentation files themselves. This would e.g. allow adding new "prototype" framework versions for documentation purposes for internal use, without publicizing to the world the name/version of the new framework. Or it could be more space efficient, or a non-XML format, or...

It also means that should we want to transition *away* from ECMA XML -- Markdown? -- the framework version information would already be "separate", and wouldn't hinder such a transition.

**Comment by jonpryor** [comment]
"Externally stored framework information" Proposal:

The primary use case is for rendering the **Version Information** section, e.g. [for `System.Type`](https://msdn.microsoft.com/en-us/library/system.type(v=vs.90).aspx#Version%20Information):

> ### Version Information
> **.NET Framework**  
> Supported in: 3.5, 3.0, 2.0, 1.1, 1.0
> **.NET Compact Framework**  
> Supported in: 3.5, 2.0, 1.0
> **XNA Framework**  
> Supported in: 3.0, 2.0, 1.0

Assuming a monodoc XSLT-like environment...

While rendering that section on the type or the members, we have access to the `<MemberSignature/>` element, so it makes sense to use that as a "key" into our framework information.

```xml
<Type Name="System.Type">
    <Member Signature="public override Type ReflectedType { get; }" Language="C#">
        <Framework Name="Xamarin.Android" Version="7.1" />
        <!-- ... -->
    </Member>
</Type>
```

...though the above assumes a single "framework" XML file. That might be the easiest way to go -- less need to probe filesystem locations while rendering the HTML -- but also means that adding a new framework will hit "shared" files in the documentation repo.

I'm not quite sure how to efficiently handle that.

**Comment by joelmartinez** [comment]
A slightly different proposal

- if `-frameworks` is present, mdoc creates a folder called `Frameworks`
- for each _frameworkName_ folder present in `path/to/frameworks`, we create an file; _frameworkName.xml_
- That XML file would contain every type and member that is available in that framework
  - This is similar to the [`index.xml`](https://github.com/mono/mono/blob/master/mcs/class/System/Documentation/en/index.xml) file, except that the purpose would be to act as a lookup for availability.
  - The list of available frameworks can simply be an enumeration of the files in the `Frameworks` folder.

The file could look as such:

```xml
<Framework Name="corefx" Version="1.0">
  <Type Name="System.Type">
    <Member Signature="public override Type ReflectedType { get; }" Language="C#" />
  </Type>
</Framework>
```

This way, we don't have to reproduce the framework name/version for every single member, and the single "framework" file doesn't become enormous from all of the duplication ... thoughts?

**Comment by joelmartinez** [comment]
I should also mention that the rendering of availability is not the only use case ... We also want to support filtering based on framework and version:

![image](https://cloud.githubusercontent.com/assets/90380/22114701/6a45e0e8-de38-11e6-8a3e-7740d2ee41b1.png)

That's another use-case that is simplified by my proposal, since you only have to list the types and/or members in that framework file when the user opts to filter the UI.

**Comment by jonpryor** [comment]
> A slightly different proposal

That's fine too.

I don't think the file format really matters, per-se. The more important question is where the information should reside, *within* the documentation files or separately.

If we agree on "separately", the file format should be...whatever makes rendering that information easier.

**Comment by dend** [comment]
@jonpryor @joelmartinez I would also add that we have a set of network monikers: https://docs.microsoft.com/en-us/nuget/schema/target-frameworks - something to consider for folder naming/parsing.
