### ISSUE TITLE
Add support for a Markdown <format> option

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#14]
In our publishing system, we have a lot of Markdown content that we are exposing to end-users. To embed it in ECMA XML, we use `<format type="text/markdown">` and then the publishing system interprets it as such.

While this works for our needs, this is a larger ask for the Xamarin toolset to support interpreting Markdown from the `<format>` element for things such as `mdoc export-html`.

**Comment by jonpryor** [comment]
Are you sure you *exactly* want `<format type="text/markdown"/>`; the intended workflow for `<format/>` is for "inline content" in the specified format:

```xml
<format type="text/html">
   <h2>Title</h2>
    <p>something something <a href="...">something</a>.</p>
</format>
```

Then when `mdoc export-html` renders *to html*, the above `<format/>` block is included. *Other* `<format/>` blocks with a *non-* `text/html` format would be *skipped*. Doing this, you can "inline embed" content specific for both HTML and e.g. man pages.

(The *real* purpose was to simplify importing HTML documentation into ECMA XML documentation, wrapping HTML constructs which couldn't be represented in ECMA format within a `<format/>`.)

With that in mind, `<format type="text/markdown"/>` would only make sense if you were rendering the ECMA XML *to Markdown*:

```xml
<Docs>
  <remarks>
    <para>This member does...something.</para>
    <format type="text/markdown">
# Some Header
Lots of Markdown-formatted text, *inline* within the enclosing ECMA XML document.
    </format>
  </remarks>
</Docs>
```

Then if we had a `mdoc export-markdown` command -- which we don't -- then the above `<format type="text/markdown" />` block would be included in the generated Markdown content.

This is *almost certainly* **not** what you want. I believe what you *actually* want is a tag to *import* content *from* Markdown.

**Comment by jonpryor** [comment]
> I believe what you *actually* want is a tag to *import* content from Markdown.

Let's build on this thought. :-)

There is only one current element that *imports* content into ECMA XML: the `<code/>` element takes an optional `src` parameter, which allows importing the specified file, or a subset of that file:

```xml
<code lang="C#" src="path/to/examples.cs#Region Within The File" />
```

The above `<code/>` is interpreted by `mdoc update`, and when `mdoc update` executes it will find the file `path/to/examples.cs`, then look for the `#region Region Within The File`, and include all content until the next `#endregion` is found. Assuming an `example.cs` of:

```csharp
// examples.cs
partial class MyUnitTests {
  [Test]
  public void Addition()
  {
#region Region Within The File
    Console.WriteLine ("Hello, world!");
#endregion
  }
}
```

Then after running `mdoc update`, we'd have the content:

```xml
<code lang="C#" src="path/to/examples.cs#Region Within The File">
    Console.WriteLine ("Hello, world!");
</code>
```

[Cadenza](https://github.com/cadenza/cadenza) uses this so that [documentation](https://github.com/cadenza/cadenza/blob/bdb38a8/src/Cadenza/Documentation/en/Cadenza/Maybe.xml#L77-L83) can show sample usage based on [unit tests](https://github.com/cadenza/cadenza/blob/bdb38a8/src/Cadenza/Test/Cadenza/MaybeTest.cs#L100-L107)

**Comment by jonpryor** [comment]
> I believe what you *actually* want is a tag to *import* content from Markdown.

Let's finish this thought.

You don't want `<code/>`, and there are no other elements which handle importing. Therefore, perhaps we should add one?

```xml
<import type="text/markdown" source="path/to/file/to/import.md" />
```

I think this is what you actually want. `mdoc export-html` could resolve the files referenced by `//import/@source`. If `//import/@type` is `text/html`, it would just "pass-through" the content. If `@type` is `text/markdown`, we could use one of the numerous Markdown formatters to convert to HTML, then insert the resulting HTML into the final document.

**Naming**: I'm not *quite* sure `<import/>` is a good name, as it doesn't specify *what* is doing the import. Perhaps `mdoc update` should do the import, for example? (It shouldn't, but `mdoc update` is what imports `//code/@src`, so there's room for confusion.)

I'm open to alternate suggestions. Perhaps `<export/>`? `<export-insert/>`?

**Comment by dend** [comment]
@jonpryor I think ultimately we want to maintain a single file for content, in this case the ECMA XML. The ask for the Markdown include *in the ECMA XML* stems from the fact that we actually export a lot of content from an old publishing system into Markdown. 

With much content in Markdown format, we thought about the possibility of having those in separate files, and then have an `<import>`-like feature like you described above, but we ran into the maintainability issue - writers have to keep up with ~200k+ reference content pieces, and jumping between the XML file and the respective Markdown import would be extremely cumbersome and is prone to cause a lot of confusion for the end users, who wouldn't be sure where to go to contribute content.

In this case, we have considered the option of simply importing the existing Markdown content into the XML through `<format type="text/markdown">` - the XML itself will be then translated to YAML and pushed to our new publishing system.

Generally, I would prefer following the ECMAXML convention when it comes to references, formatting, parameters et al, but Markdown in this case offers an easy way for even those that are not familiar with the XML to add some relevant rich content within a single file.

Also worth mentioning that we do not rely on `mdoc export-html` but only on `mdoc update` to get the XML, and then post-process with our own tooling.

**Comment by jonpryor** [comment]
I stand corrected. Very interesting. :-)

**Comment by joelmartinez** [comment]
@dend I was looking at this particular item, and it occurred to me that you're already importing the markdown content on your side

> Also worth mentioning that we do not rely on mdoc export-html but only on mdoc update to get the XML, and then post-process with our own tooling.

So with that in mind, I'm removing this item from [v5.0 Preview](https://github.com/mono/api-doc-tools/milestone/1). I specifically named the milestone "Preview", because there are still a few follow-on tasks that I'll need to complete before considering this a proper 5.0 release for the broader community ... but those tasks don't affect you :)

**Comment by dend** [comment]
@joelmartinez sounds good!
