### ISSUE TITLE
[mdoc][research] Adding support for <inheritdoc/>

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#152]
This a feature gap between `mdoc` and Sandcastle. According to [the Sandcastle documentation](http://tunnelvisionlabs.github.io/SHFB/docs-master/SandcastleBuilder/html/79897974-ffc9-4b84-91a5-e50c66a0221d.htm):

>The use of the `<inheritdoc />` custom XML comments tag can help minimize the effort required to document complex APIs by allowing common documentation to be inherited from base types/members.

**Comment by joelmartinez** [comment]
I have counter-proposal 😄 What if instead of supporting `<inheritdoc>`, this behavior was implicitly on by default?

1. If a member contains documentation (`summary`, `remarks`, etc), then this would be used.
2. If no explicit documentation, and the member is overridden, use the base implementation's docs (if available).
3. If no base docs, and there is an interface member with docs, use those (if available).

There are a few reasons that I would prefer *not* to adopt this feature in _mdoc_:

- An implicit "implementation" of this is easier for the developer/writer, and more useful for the reader. 
    - Rather than depending on the developer/writer to remember to put this tag there, it automatically brings in the information for the user of the library to take advantage of.
    - Imagine implementing a complicated interface ... you'd have to include `/// <summary><inheritdoc /></summary>` on *every single member*! 
- Not supported in IntelliSense ... Visual Studio shows nothing when you use `<inheritdoc />` in the summary.
- It's Complicated. Looking at the linked sandcastle documentation, particularly, the `cref` and `select` features of `inheritdoc` adds user-supplied "code" to be run at render-time ... what happens if the `cref` doesn't exist? or if the xpath returns nothing (or returns multiple)?
- Downstream work would be needed *anyways*.
    - Adding support for `inheritdoc` in _mdoc_ is "easy" ... we just have to modify our XSD to allow it.
    - The work to **interpret** `inheritdoc` would still have to happen in either _ecma2yaml_ or _docfx_.

So, to get to this better future:

- Modify _ecma2yaml_ to implement the rules described in the first numbered list above. It would just automatically include that documentation in the resulting YAML when appropriate.
    - Remember that **work here already needs to occur either way**.
- Modify _mdoc_'s `export-msxdoc` subcommand to also follow the same rules
    - This subcommand converts an EcmaXML docset into the equivalent output from `/doc`, thus allowing a library authors who don't use `///`, to ship authored docs in nugets (for example).
- (optionally?) Get with stakeholders for VS, VSMac, and OmniSharp to also implement the same rules for IntelliSense.

I believe this to be a better course of action that will make a better experience for library authors, writers, and users ... and lead them into the Pit of Success. Of course, if the overwhelming consensus is that we should just implement `inheritdoc`, we can do that. For one last note, I'll mention that there have been various requests over the years for visual studio/C# to support `inheritdoc` (latest [here](https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/3745102-add-intellisense-support-for-the-inheritdoc-ta)), and even in the comments there, some folks propose (essentially) the same thing ... for `inheritdoc` to not be necessary, and for the actual functionality to be implicitly available.

thoughts @jonpryor, @conceptdev, @lobrien ?

**Comment by davidmatson** [comment]
I like the idea of "it just works", but I'm also wondering whether there are benefits of supporting an explicit statement as well. For example, consider:
```c#
public override string ToString()
{
    return base.ToString();
}
```

If you want to call base, you do so explicitly, and this explicit control has some advantages. The same might be true of `<inheritdoc/>` with respect to scenarios like taking the params from base but tweaking summary and remarks.

One of the biggest reasons I like the explicit `<inheritdoc/>` is for CR purposes - it makes it clear to other reviewers (and myself) that I didn't forget to add documentation - I made an intentional decision to re-use the base class/interface documentation as-is. Similarly, having an explicit indication might also be a better way to address compiler support such as CS1591 (warning when documentation is missing on a public type).

Having `<inheritdoc/>` on by default would likely be useful, but for the above reasons I wonder if having an explicit option is also worthwhile.

**Comment by davidmatson** [comment]
I'm content punting on things like `cref` and `select` - if there's significant value, I figure we can always re-examine later.

>Would this work for you @davidmatson / @dend ?
Works for me. If others like the idea of having it on by default, that won't bother me either; I'd just prefer that we also have the explicit option.

**Comment by dend** [comment]
@joelmartinez @davidmatson :shipit: looks good to me, and in this case, just want to clarify - when `mdoc` runs, how will it interpret `<inheritdoc>` tags?

**Comment by joelmartinez** [comment]
@dend well _mdoc_ would simply ignore `inheritdoc`, as the transformation happens downstream in either model (ie. when the content is rendered).
