### ISSUE TITLE
Support metadata in ECMAXML

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#153]
We've seen that in some workflows, it might make sense to support a `<metadata>` element inside the ECMAXML, that acts as a set of key-value pairs that might be needed for the documentation publishing pipeline.

**Comment by joelmartinez** [comment]
If we decide to do this, _mdoc_ would require only two changes:

- Modifying the XSD to allow `/Type/Metadata/Meta` elements.
- Validation integration tests
- Add to the [sort order](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/MDocUpdater.cs#L2023).

So as changes go, this is relatively simple to add.

**Comment by TianqiZhang** [comment]
To avoid setting the same meta on each child, we can probably introduce a "applyToChildren" or "toBeInherited" attribute for each <Meta> so that all members can get the same meta from the parent type and so on.

**Comment by joelmartinez** [comment]
So far, the only and initial use-case that has brought up the need for attaching metadata, has been at the file level ... I propose that we limit this feature so that `<Metadata>` is only valid at the type level (which equates to the file level for EcmaXML). If the need arises in the future, we can easily modify the XSD to account for metadata at lower level nodes, and inheritance features like you propose.

YAGNI :)

**Comment by dend** [comment]
@joelmartinez @TianqiZhang totally OK with having the metadata at the file level (aka on type).
