### ISSUE TITLE
[mdoc] Implementation details are not shown on members

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#158]
We have scenarios where certain members are actually implementations of the inherited interface. As an example:

![image](https://user-images.githubusercontent.com/1389609/32751819-e472efb8-c87b-11e7-90c5-957ad31ca800.png)

Here, we can see that the property implements `IBuildSettings.ApplicationUrl`. When we go to the version of [this page on docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/api/Microsoft.Build.Tasks.Deployment.Bootstrapper.BuildSettings.ApplicationUrl?view=netframework-4.7), this information is missing because it's not included in ECMAXML.

This should be part of the **M3** work.

**Comment by joelmartinez** [comment]
@dend hmm, other than the interface details being at the type level, there's not currently any instance where a `Member` node includes any information about the interface implementation. Are you saying you'd like to see something along the lines of:

```
<Member ...>
    ...
    <Implements>P:ISome.Property</Implements>
</Member>
```
?

**Comment by dend** [comment]
@joelmartinez yes, that would be good. It's much easier to parse and understand from the model perspective.

**Comment by joelmartinez** [comment]
Hi @mpMelnikov ... it looks like this feature breaks with a key not found exception under when a class implements a destructor (which compiles into an override of `Object.Finalize`). After some investigation, I found that adding `~Class6(){}` to `TestInterfaceImplementation/Class6.cs` reproduces the error (to give one example).

I _think_ that since `Finalize` is a special case, we should add a check to `DocUtils.IsExplicitlyImplemented` to watch for a `protected` method named `Finalize`, with one override who's `DeclaringType` is `System.Object`. But since you implemented the feature you've probably had this issue a bit more top-of-mind ... let me know what you think.

/cc @dend

**Comment by mpMelnikov** [comment]
Hi @joelmartinez!
I've suggested a slightly different solution here #183.
As we show only implementations of the inherited interfaces we shouldn't try to add implemented member of a class `Object`. I've considered the option to check in `IsExplicitlyImplemented` if `DeclaringType` of any implemented member is an interface, but the suggested solution seems to be faster. And yes, we will need to check `Finalize` as a special case if we decide to show overridden methods of classes in `<Implements>` node.

**Comment by TianqiZhang** [comment]
@joelmartinez @dend similar to this one, we also need override info to indicate which parent method does current method overrides. Is there already an issue tracking it?

**Comment by joelmartinez** [comment]
@TianqiZhang there's not currently an issue tracking a request like this that I'm aware of
