### ISSUE TITLE
[mdoc] Handle different inheritance hierarchy

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#16]
`System.IO.Stream` has different inheritance hierarchy in .NET Fx and Core. See the definition here:
https://github.com/dotnet/coreclr/blob/release/1.1.0/src/mscorlib/src/System/IO/Stream.cs#L34

There is a conditional directive to control whether the `Stream` class derives from `MarshalByRefObject` or not. So in .NET Fx, it’s derived from `MarshalByRefObject` but in .NET core it’s not. 

This should also be handled by `mdoc`.

**Comment by joelmartinez** [comment]
Hmm, so this complicates matters a bit. 

The first question to tackle here, is that we currently have a single file, based on the type name, to represent a type ... unlike at the `<Member>` level, where we can simply make another node. So first let's define what do we *want* to happen here:

1. Do we want to have _two files_ in this case?
    - If so, what do we use for a file naming convention in cases where there is more than one "source of truth" for a given type: `System.IO/Stream.cs` and `System.IO/MarshalByRefObject-Stream.cs`
    - The problem with the approach above is that all downstream clients of this file system will now have to be aware of this new file convention.
    - Also, every other member that is otherwise unaffected will have to have its documentation duplicated in both files.
1. Do we want to have some sort of "framework qualifier" on any given XML node that can specify that something exists only in a given framework?
1. Or, do we want to introduce a new "node type" that could act as a sort of mini-conditional statement ... something like  
    ```xml
    <ConditionalValue Framework="netcore">
      <True>System.MarshalByRefObject</True>
      <False>System.Object</False>
    </ConditionalValue>
    ```


I'm _tentatively leaning_ towards the second solution, where we have something like an attribute called `FrameworkAlternate`, which would mean that the value without the attribute is the one to use by default, and otherwise you should use the one that matches the framework that is being displayed at the moment:

```xml
  <Base>
    <BaseTypeName>System.Object</BaseTypeName>
    <BaseTypeName FrameworkAlternate="netcore">System.MarshalByRefObject</BaseTypeName>
  </Base>
  <Interfaces>
    <Interface>
      <InterfaceName>System.IDisposable</InterfaceName>
    </Interface>
  </Interfaces>
```
In a similar vein, we could introduce a `FrameworkExclude` attribute for situations like attributes, where an attribute is everywhere but a given framework ... as is the case with the `Serializable` attribute, which doesn't exist in `netcore` yet.
```xml
  <Attributes>
    <Attribute FrameworkExclude="netcore">
      <AttributeName>System.Serializable</AttributeName>
    </Attribute>
  </Attributes>
```

But I'm not _in love_ with the idea/solution ... thoughts, @jonpryor ?

**Comment by jonpryor** [comment]
@joelmartinez: I like the `//BaseTypeName/@FrameworkAlternate` idea, though I think it can be shortened to just `//BaseTypeName/@Framework` or `@FrameworkName`.

I can see how this would reasonably work in the context of #13, where the framework name could be automatically deduced and used, based on the input directory structure.

A problem, however, is that -- again in the context of #13 -- we now plausibly have an assembly processing *order* dependency. Which assembly picks the non-`@Framework` value? The first one processed, of course? Alternatively, the "default"/non-`@Framework` value could be the type which is present in *most* assemblies, but what happens when you have a tie?

I like the idea. I'm not sure how to make it integrate sanely with tooling to provide sane, automatic, defaults. :-/

The `//Attribute/@FrameworkExclude` attribute I'm less fond of, largely because it has an inverse logic relation: it lists the frameworks it's *not* in, as opposed to the frameworks it's *in*. Though this distinction might make hand-edits easier, but also means that `mdoc` will need to check for the attribute and not replace the element, if the attribute is found.

**Comment by dend** [comment]
Just like @jonpryor mentioned, I think `//BaseTypeName/@Framework` sounds a reasonable take on this. 

My only comment would be to add the attribute to all elements *if* a framework is specified when `mdoc` runs. Which adds the complexity related to a type/member being available in several frameworks/attributes.

Can we formalize it as:

```
<Base>
    <BaseTypeName>System.Object</BaseTypeName>
    <Frameworks>
           <Framework id="net451" />
           <Framework id="netcore10" />
    </Frameworks>
 </Base>
<Base>
   <BaseTypeName>System.MarshalByRefObject</BaseTypeName>
    <Frameworks>
           <Framework id="net44" />
           <Framework id="netcore09" />
    </Frameworks>
</Base>
```
