### ISSUE TITLE
[mdoc] Missing API for VisualC reflected binary

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#200]
There is a missing parameter detail for [`ReverseRandomAccessIterator<TValue>.GreaterThanOrEqual(ReverseRandomAccessIterator) Operator`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualc.stlclr.generic.reverserandomaccessiterator-1.op_greaterthanorequal?view=netframework-4.7)

![image](https://user-images.githubusercontent.com/1389609/34532513-3ce8bf12-f06b-11e7-9264-78b50c28ffd2.png)

The [MSDN page](https://msdn.microsoft.com/en-us/library/bb359755(v=vs.110).aspx(d=robot)) showcases that it should be `Microsoft.VisualC.StlClr.Generic.ReverseRandomAccessIterator<TValue>` and not `
Microsoft.VisualC.StlClr.Generic.ReverseRandomAccessIterator`.

[Reference XML fragment](https://github.com/dotnet/docs/blob/master/xml/Microsoft.VisualC.StlClr.Generic/ReverseRandomAccessIterator%601.xml#L533):

![image](https://user-images.githubusercontent.com/1389609/34532609-9415fb88-f06b-11e7-8175-c6f3765dadcc.png)

**Comment by asokolovskiy15** [comment]
@dend 
Could you please share binary file for further investigate and solving this issue?

**Comment by dend** [comment]
@asokolovskiy15 sure thing - you can find it [here](https://apidrop.visualstudio.com/binaries/binaries%20Team/_git/binaries?path=%2Fdotnet%2Fnetframework-4.7.2%2FMicrosoft.VisualC.STLCLR.dll&version=GBmaster&_a=contents). You can clone the repo for the full set of binaries that are necessary.

**Comment by asokolovskiy15** [comment]
@dend seems like, we don't have an access to this link 
401 
NOT AUTHORIZED

Could you please resolve it?

**Comment by dend** [comment]
@asokolovskiy15 try again? I just added you to the repo, apologies for the inconvenience!

**Comment by mairaw** [comment]
I can't see this fix on the latest run: 
https://review.docs.microsoft.com/en-us/dotnet/api/microsoft.visualc.stlclr.generic.reverserandomaccessiterator-1.op_greaterthanorequal?view=netframework-4.7.2&branch=pr-en-us-293

**Comment by dend** [comment]
@mairaw @joelmartinez the interesting part here is that we actually have the generic version of the referenced entity: **https://review.docs.microsoft.com/en-us/dotnet/api/Microsoft.VisualC.StlClr.Generic.ReverseRandomAccessIterator-1?view=netframework-4.7.2&branch=pr-en-us-293**

**Comment by joelmartinez** [comment]
re-opening this ... will review why the non-generic one isn't being documented

**Comment by mpMelnikov** [comment]
Hi @joelmartinez!
I received an e-mail notification about this issue and investigated it a little bit. 
Unfortunately, I can't open mentioned URLs anymore (404 error), so I used the latest commit from `master` branch (it was done by @dend [2 days ago](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.VisualC.StlClr.Generic/ReverseRandomAccessIterator%601.xml)). 
I've found out two interesting facts.
1. If we run the command `update -o VisualC Microsoft.VisualC.STLCLR.dll` on the empty folder, we get such node in `ReverseRandomAccessIterator'1.xml`:
```xml
<Member MemberName="op_GreaterThanOrEqual">
<!--... -->
      <Parameters>
        <Parameter Name="_Right" Type="Microsoft.VisualC.StlClr.Generic.ReverseRandomAccessIterator&lt;TValue&gt;" />
      </Parameters>
<!--... -->
```
2. When we run the same update command on `ReverseRandomAccessIterator'1.xml` from `master` branch. We get two `op_GreaterThanOrEqual` nodes:
```xml
<!--The old one with incorrect parameter type-->
<Member MemberName="op_GreaterThanOrEqual">
<!--... -->
      <Parameters>
        <Parameter Name="_Right" Type="Microsoft.VisualC.StlClr.Generic.ReverseRandomAccessIterator" />
      </Parameters>
      <Docs>
        <param name="_Right">The iterator to compare with the left-side iterator.</param>
<!--... -->
```
```xml
<!--The new one with correct parameter types-->
<Member MemberName="op_GreaterThanOrEqual">
      <Parameters>
        <Parameter Name="_Right" Type="Microsoft.VisualC.StlClr.Generic.ReverseRandomAccessIterator&lt;TValue&gt;" />
      </Parameters>
      <Docs>
        <param name="_Right">To be added.</param>
        <summary>To be added.</summary>
        <returns>To be added.</returns>
        <remarks>To be added.</remarks>
      </Docs>
<!--... -->
```

Is it the expected behavior of `update` command? 
1. If so, do @dend and @mairaw have the same result XMLs?
2. If not, what is an expected behavior?

**Comment by dend** [comment]
@mpMelnikov @joelmartinez looking at this document:
https://github.com/dotnet/dotnet-api-docs/blob/master/xml/Microsoft.VisualC.StlClr.Generic/ReverseRandomAccessIterator%601.xml#L731

I only see one instance of `op_GreaterThanOrEqual` there, and it seems like it is the one with the incorrect parameter. The behavior above is not expected, though. At least not if the same API is coming from the same assembly version.

**Comment by mpMelnikov** [comment]
> The behavior above is not expected, though. At least not if the same API is coming from the same assembly version.

I've investigated it again, two copies of `op_GreaterThanOrEqual` member appear because I didn't set a special flag `-delete`, which is responsible for "Delete removed members from the XML files." If I set this flag, there is only a new version of `op_GreaterThanOrEqual` with correct type of `_Right` parameter:
```xml
    <Member MemberName="op_GreaterThanOrEqual">
      <MemberSignature Language="C#" Value="public bool operator &gt;= (Microsoft.VisualC.StlClr.Generic.ReverseRandomAccessIterator&lt;TValue&gt; _Right);" />
      <MemberSignature Language="ILAsm" Value=".method public hidebysig specialname instance bool op_GreaterThanOrEqual(class Microsoft.VisualC.StlClr.Generic.ReverseRandomAccessIterator`1&lt;!TValue&gt; _Right) cil managed" />
      <MemberType>Method</MemberType>
      <AssemblyInfo>
        <AssemblyVersion>2.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>System.Boolean</ReturnType>
      </ReturnValue>
      <Parameters>
        <Parameter Name="_Right" Type="Microsoft.VisualC.StlClr.Generic.ReverseRandomAccessIterator&lt;TValue&gt;" />
      </Parameters>
      <Docs>
        <param name="_Right">To be added.</param>
        <summary>To be added.</summary>
        <returns>To be added.</returns>
        <remarks>To be added.</remarks>
      </Docs>
    </Member>
```

It's really interesting why we get different XMLs. How I'm trying to reproduce it:
1. Updated mdoc to the latest master branch [commit](https://github.com/mono/api-doc-tools/commit/c85d6d653ea1439ae769e1655234f028f13799c7).
2. Downloaded `Microsoft.VisualC.STLCLR.dll` from [here](https://apidrop.visualstudio.com/binaries/binaries%20Team/_git/binaries?path=%2Fdotnet%2Fnetframework-4.7.2%2FMicrosoft.VisualC.STLCLR.dll&version=GBmaster&_a=contents).
3. Downloaded `Microsoft.VisualC.StlClr.Generic`, `Microsoft.VisualC.StlClr` folders and `index.xml`, `ns-Microsoft.VisualC.StlClr.Generic.xml`, `ns-Microsoft.VisualC.StlClr.xml` files  from [here](https://github.com/dotnet/dotnet-api-docs/tree/master/xml) to the folder `VisualC`.
4. Ran the command `update -o VisualC -delete Microsoft.VisualC.STLCLR.dll`
5. Got the mentioned result

@dend Could you please share how you reproduce it? Maybe we run different commands?

cc: @joelmartinez @mairaw

**Comment by mimisasouvanh** [comment]
Internal [bug](https://ceapex.visualstudio.com/Engineering/_workitems/edit/167410) logged.
