### ISSUE TITLE
[mdoc] Do not document APIs that are specially-tagged

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#212]
There are cases where types are marked with `[CompilerGenerated]` and `[TypeIdentifier]`, and those should not be documented.

cc: @aarnott

**Comment by joelmartinez** [comment]
Thanks for the information @AArnott and @dend. So ... just to be 100% clear in the requirements here:

> Any time the same type is found as an embedded type in another assembly (identifiable by the presence of the two attributes mentioned in the issue description)

Is there anything else special about these types, other than the presence of these two attributes? Could I, for testing purposes, make a type and apply these attributes manually; or can it only be done through some special thing by the computer (I'm asking so that I can design the tests that will go along with this implementation). 

---
This is at the type level only, right? so in the example in the screenshot above, when _mdoc_ is processing `Microsoft.VisualStudio.ProjectSystem.VS.Implementation.dll`, I should *filter out* the type `IVsTelemetrySession`, when I see that it has `CompilerGenerated` and `TypeIdentifier` applied to it?

---

Thanks for the clarifications :)

**Comment by AArnott** [comment]
> Is there anything else special about these types, other than the presence of these two attributes? 

There are a bunch of requirements on the types in general to be embeddable. But all it takes is the presence of the `[TypeIdentifier]` attribute on a type for the compiler to refuse to let anyone outside the assembly use it.

> Could I, for testing purposes, make a type and apply these attributes manually; or can it only be done through some special process by the compiler (I'm asking so that I can design the tests that will go along with this implementation).

I just tried it. Older versions of the C# compiler wouldn't even let you apply the attribute. Now it apparently lets you, but as soon as you apply `[TypeIdentifier]` then no one outside the assembly can use
it (our compilers block it). So yes, you should be able to write tests for it.

> This is at the type level only, right?

According to [this doc](https://docs.microsoft.com/en-us/dotnet/framework/interop/type-equivalence-and-embedded-interop-types) it applies to interface, enum, struct and delegate types.

**Comment by terrajobst** [comment]
Completely agree with @AArnott here. No-PIA based copies shouldn't be doc'ed because they are effectively an implementation detail of the library that ended up embedding them. Given how extremely noisy COM interop already is, hiding this goo is definitely the desired the outcome. Of course, we should still document the original definitions (PIA) but not he no-PIA embedded copies. And that's what the attributes help with.

**Comment by joelmartinez** [comment]
Thank you @AArnott and @terrajobst for chiming in ... so to resolve this, I'm going to make it so that if _mdoc_ encounters a `TypeIdentifier` attribute on *any type*, it will simply refuse to enumerate and document it.

**Comment by AArnott** [comment]
>on _any type_

type _or delegate_.
