### ISSUE TITLE
FrameworkAlternate param erroneously removed

### ISSUE THREAD

**Issue by joelmartinez** [mono/api-doc-tools#222]
You can see in this case [here](https://github.com/dotnet/dotnet-api-docs/pull/10/files/b654cf02bbd267ec1f263ddc29ce1637bbd2b8c8#diff-94dfd0cfc74c0212096cc3ccdcf7b00b), that although both parameter names exist in different frameworks (as seen due to multiple `MemberSignature` elements being present), the `supports` param was removed in the diff.

Both should be present when they exist in different frameworks.

**Comment by mairaw** [comment]
Does this mean that we'll have to document the parameter twice? I actually prefer the new name used since this is the most common one (and it would help to bring over the missing content from our old system).

But I thought it was strange that netframework-4.7.2 was also not added to the list of FrameworkAlternate for the generatorSupport param. It should be the same as all previous versions.

**Comment by joelmartinez** [comment]
This particular instance of the missing `supports` parameter is still occurring after the latest release that includes the previous attempted fix.
