### ISSUE TITLE
SerializableAttribute for System.String should be in fullly qualified name

### ISSUE THREAD

**Issue by TianqiZhang** [mono/api-doc-tools#365]
See in [System.String.xml#L56](https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System/String.xml#L56):

`<AttributeName>Serializable</AttributeName>` is not a fullly qualified name as other attributes.

```xml
<Attributes>
<Attribute FrameworkAlternate="netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
<AttributeName>System.Runtime.InteropServices.ComVisible(true)</AttributeName>
</Attribute>
<Attribute FrameworkAlternate="netframework-1.1;netframework-2.0;netframework-3.0;netframework-3.5;netframework-4.0;netframework-4.5;netframework-4.5.1;netframework-4.5.2;netframework-4.6;netframework-4.6.1;netframework-4.6.2;netframework-4.7;netframework-4.7.1;netframework-4.7.2;xamarinandroid-7.1;xamarinios-10.8;xamarinmac-3.0;netframework-4.8">
<AttributeName>Serializable</AttributeName>
</Attribute>
</Attributes>
```

**Comment by joelmartinez** [comment]
@TianqiZhang, @dend, @adkinn Currently, mdoc strips off the trailing `Attribute` suffix when it "renders" the attribute string, using this code:

```csharp
                string name = attribute.GetDeclaringType ();
                if (name.EndsWith ("Attribute")) name = name.Substring (0, name.Length - "Attribute".Length);
                yield return prefix + name + a2;
```

The question is, **should** the `AttributeName` here be `System.Serializable`, or `System.SerializableAttribute`, which is the full type name?

I **assume** the answer is `System.Serializable`, since that's what we're currently doing for the other attributes; you can see this in action on any page that shows attributes: [example](https://docs.microsoft.com/en-us/dotnet/api/system.serializableattribute?view=netframework-4.7.2). Here we see `[System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Struct | System.AttributeTargets.Enum | System.AttributeTargets.Delegate, Inherited=false)]`, which results in a proper link to `System.AttributeUsageAttribute`:

![image](https://user-images.githubusercontent.com/90380/48077406-44899e80-e1b5-11e8-9d49-8c4e553d1c86.png)

I'm **guessing** that either ecma2yaml, or the front-end templates are parsing these and adding the `Attribute` suffix back in to generate that list of links?

**Comment by TianqiZhang** [comment]
@joelmartinez yes, ECMA2Yaml will try append `Attribute` suffix if the full name cannot be resolved. So `System.Serializable` will be fine.
