### ISSUE TITLE
Need to retain type forward information for forwarded types

### ISSUE THREAD

**Issue by TianqiZhang** [mono/api-doc-tools#373]
This is related to #103 and #342. Now that both of them are closed, there's still one missing piece.

Take `Dictionary<TKey,TValue>` as an example, the full assembly info should include information like in below 2-dimensional matrix:

| assembly/frameworks | .Net Framework | .NET Core | .NET Standard |
|-------------------------|-------------------|------------|-----------------|
| System.Collections  | ❌              | ✔️         | ❌             | 
| mscorlib                  | ✔️              | ❔           | ❌             | 
| netstandard             | ❌              | ❌         | ✔️             | 

I can somehow put together all information in this matrix except for the ❔. Now we are showing ❔ as ✔️ too, however it should be "forwarded". 

I'm wondering if there's a good way to include this information in ECMAXML.

**Comment by joelmartinez** [comment]
@TianqiZhang as discussed in that other thread, the `mscorlib` in netcore-2.1 is _currently_ explicitly listed in the list of assemblies that are part of that moniker, so that's part of the confusion. However, if it were to be moved into the dependencies folder, it would be used for resolving, and **excluded** from the list in the frameworks index file.

Would that be enough to properly figure out how to mark the info in that matrix? If an assembly is in the frameworks index file, then it's ✔️, but if it's _only_ listed on the type/member `AssemblyInfo`, then that assembly would be forwarded?

**Comment by TianqiZhang** [comment]
@joelmartinez I see what you mean. @mairaw is there a special reason for `mscorlib.dll` to sit in netcore-2.1 folder in binaries repo?

**Comment by mairaw** [comment]
That's the drop I get from the PU. It includes facades as well.

**Comment by joelmartinez** [comment]
can we 100% guarantee that a façade assembly is **defined** by the fact that it only contains exported types? And if so, that mdoc would **never** want to include this assembly in the list of assemblies on the frameworks index file?

I don't know … that seems like one of those things that is just asking to be proved wrong :P 

@dend, thoughts?

**Comment by TianqiZhang** [comment]
@joelmartinez I'd like to request mdoc to add a flag for these facade assemblies in frameworks index file, so that downstream can have the flexibility to handle them for different requirements.

Per my understanding, there are at least 3 places that used assembly info:
1. page apiscan metadata. Facades are currently there, and they should be. ✔️
2. assemblies list on top of the page. Facades are currently there, however they shouldn't be.❌
3. intellisense build. Facades are excluded for now, with an additional moniker2assembly mapping json that is generated in CI. We'd like to get rid of this json and directly use mdoc's output.🙋

If mdoc can flag out the facade assemblies, it will greatly help in No.2 and No.3 scenarios. cc @mairaw @dend

**Comment by joelmartinez** [comment]
@TianqiZhang understood. I would still like to get verification that a façade assembly **is defined by** only containing exported types and nothing else (perhaps @terrajobst could comment?).

Implementation Notes:

- The attribute would be added [here](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/Updater/Frameworks/FrameworkIndex.cs#L108)
- [This data structure](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/Updater/Frameworks/FrameworkEntry.cs#L58) (used in the previous point), would have to be enhanced to include the façade flag (a bool).

**Comment by joelmartinez** [comment]
@TianqiZhang wouldn't it also need to tell what assembly it was forwarded *to* ?

**Comment by TianqiZhang** [comment]
@joelmartinez oh what I meant by `forwarded="true"` is that the current type is not actually **in** this assembly, it is forwarded from somewhere else. How about I change it to `forwardedFrom` and fill it with the assembly name where this type is **really** from? Like this:

```xml
  <AssemblyInfo>
    <AssemblyName>mscorlib</AssemblyName>
    <AssemblyVersion>1.0.5000.0</AssemblyVersion>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <AssemblyVersion>2.0.5.0</AssemblyVersion>
    <AssemblyVersion>4.0.0.0</AssemblyVersion>
    <AssemblyVersion forwardedFrom="mscorlib" frameworkAlternative="netcore-2.1;netcore-2.2">4.0.0.0</AssemblyVersion>
  </AssemblyInfo>
```

**Comment by TianqiZhang** [comment]
@joelmartinez any thoughts on this?

**Comment by joelmartinez** [comment]
yeah, something like that should definitely be possible … would definitely make it clearer.

**Comment by joelmartinez** [comment]
mdoc 5.7.4.10 (in this PR https://github.com/mono/api-doc-tools/pull/432) will add a feature that will make *this* enhancement infinitely easier to implement. You can see the initial implementation here:
https://github.com/mono/api-doc-tools/pull/432/commits/db8a85e76dcd30835729baca25a452e5f4c5ffc3#diff-cf20fb82aaef409362c2feac6390110aR23

Essentially, the `FrameworkTypeEntry` now has a data structure that lets you answer the following questions:

- What assemblies is this type included in
- What assemblies are forwards

This information is at the moniker/framework level. It still doesn't *fully* answer the questions at the member level though, so a bit more work will be necessary ... we will probably have to rethink how we track these assembly references, because a type/member might be in an assembly in one moniker, but forwarded to another in another. I'm tempted to say that we need to move this into the framework xml file, but those files are already so huge.

More planning TBD

**Comment by TianqiZhang** [comment]
@joelmartinez this is such great news! From the perspective of displaying the `assemblies` metadata and generating intellisense files, type level information is probably already enough, since "type-forwarding" only happens at type level anyway, there's no "member-forwarding" that we need to care about :P

**Comment by joelmartinez** [comment]
@TianqiZhang ahh, well that's great :D I wonder if we should get rid of assembly info at the member level entirely then?

**Comment by TianqiZhang** [comment]
@joelmartinez I think it's probably doable. Once we start to mark forwarded assemblies at type level in ECMAXML, I'll start to refactor the whole assembly-moniker-uid mapping logic in ECMA2Yaml, that might be a good chance to kill the dependency on member-level assembly xml node.

**Comment by joelmartinez** [comment]
This feature will be completed in PR https://github.com/mono/api-doc-tools/pull/452
