### ISSUE TITLE
FrameworksIndex files contain members of base types in inheriting types

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#39]
In the `FrameworksIndex` files, classes that inherit from base types will include the members of base types - this should not be the case, as it should be a representation of just the members belonging to the type and nothing else.

**Comment by joelmartinez** [comment]
To add a bit more context to this, I was finally able to reproduce the problem, and it comes when processing types in frameworks mode ... where a type has virtual members that are overridden in an earlier framework, but not overridden in a framework that is processed later. In this case, the corresponding `<Member>` node is removed, due to the fact that it's not overridden in that later derived type.

We will have to add a check to the member removal to check if mdoc is running in frameworks mode, and to see if a member node has been included in another previously-processed framework, before deleting it.
