### ISSUE TITLE
Last CI run added the "internal" event handler for a few APIs

### ISSUE THREAD

**Issue by mairaw** [mono/api-doc-tools#419]
The APIs added were:
- M:System.Windows.Xps.XpsDocumentWriter.raise_WritingCancelled(System.Object,System.Windows.Documents.Serialization.WritingCancelledEventArgs)
- M:System.Windows.Xps.XpsDocumentWriter.raise_WritingCompleted(System.Object,System.Windows.Documents.Serialization.WritingCompletedEventArgs)
- M:System.Windows.Xps.XpsDocumentWriter.raise_WritingPrintTicketRequired(System.Object,System.Windows.Documents.Serialization.WritingPrintTicketRequiredEventArgs)
- M:System.Windows.Xps.XpsDocumentWriter.raise_WritingProgressChanged(System.Object,System.Windows.Documents.Serialization.WritingProgressChangedEventArgs)

Here's the commit where I remove them:
https://github.com/dotnet/dotnet-api-docs/pull/1866/commits/cc77f9eff95256eca5c80613a9c595d9e2e80cbb

My understanding is that all of the following are just representation of properties getters, setters and event methods:
![image](https://user-images.githubusercontent.com/12971179/52887826-101b6c00-312e-11e9-8d47-edcb20ee54bb.png)

**Comment by joelmartinez** [comment]
Hi @mairaw so the issue here is that I think these methods were manually authored. Looking at the metadata reveals the following values:

- IsPublic = `true`
- IsSpecialName = `false`
- IsCompilerControlled = `false`
- Additionally, it doesn't have any attributes on it ... mdoc [looks for](https://github.com/mono/api-doc-tools/blob/master/mdoc/Mono.Documentation/Updater/DocUtils.cs#L439) `System.Runtime.CompilerServices.CompilerGeneratedAttribute` or `Microsoft.FSharp.Core.CompilationMappingAttribute` 

So, I'm going to close this item because I believe these items *should* be documented based on looking at the metadata ... but I'm happy to keep the discussion going if there are other considerations mdoc should take into account :)
