### ISSUE TITLE
[mdoc] Namespace names should be generated in DocID format

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#61]
Currently, namespace names are generated as standard fully-qualified names. Those should be structured as DocID FQNs instead, to be consistent with the rest of the generated documentation.

**Comment by joelmartinez** [comment]
Can you give me an example of what you're referring to? what attribute/elements is it that you would like to see different?

**Comment by dend** [comment]
As an example:
https://github.com/dotnet/docs/blob/master/xml/ns-System.Activities.Debugger.xml

Notice that the format is not the DocID convention - it doesn't have the `N:` prefix.

**Comment by joelmartinez** [comment]
ahh, yes I see what you're referring to now ... ok, so we can't change that outright, because it bucks the currently-used convention. But perhaps, if the `--use-docid` flag is used, we can do something like add a new element:

```xml
<Namespace Name="System.Activities.Debugger">
  <NamespaceSignature Language="DocId" Value="T:System.Activities.Debugger" />
  <Docs>
    <summary>Provides classes related to the system debugger.</summary>
    <remarks>To be added.</remarks>
  </Docs>
</Namespace>
```
note the `NamespaceSignature` ... this at least follows the convention found elsewhere of having a `*Signature` element with `Language="DocId"`.

or ... the workaround obviously, is to simply append `N:` to the value in `/Namespace/@Name` when querying for the document.

**Comment by dend** [comment]
I think an explicit call-out for the DocID format here is better, as it lifts the need to process this every time it goes through the pipeline. Thoughts?

//cc: @jonpryor

**Comment by jonpryor** [comment]
LGTM.
