### ISSUE TITLE
[mdoc] Generated C# signature has spaces between names and parens

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#64]
See as an example:

`<MemberSignature Language="C#" Value="public String (char* value);" />`

There should be no space between `String` and `(char`.

**Comment by joelmartinez** [comment]
It's actually this way per [Mono coding guidelines](http://www.mono-project.com/community/contributing/coding-guidelines/) ... maybe a flag to change the behavior?

**Comment by jonpryor** [comment]
Flags are evil, unless necessary. :-)

There are two issues here. Firstly, making such a change will result in possibly large diff's the next time `mdoc update` is run. Maybe that matters, maybe not; it'll be a side effect regardless.

More importantly -- and this requires more research -- will such a change *break* anything? For example, is `//MemberSignature/@Value` ever used as a "key" into some other data structure, in which *altering* it will result in not finding a prior value?

I can't quickly find an answer to that question, and it needs to be answered before we can consider this issue.

Aside: why not use a flag? Because it's madness; if you pull in XML files from multiple sources and try to process them, you would now need to know that everyone used the same flag value or things may "break" in obscure ways.

Personally, I like the space before paren.

That said, I'm also not at all fond of the semantics of `//MemberSignature/@Value`: it's a *string*. That sounds nice and all, but look at the gymnastics that `monodoc.dll` and related XSLT needs to do to to [generate members signatures](http://docs.go-mono.com/?link=M%3aSystem.Array.BinarySearch(System.Array%2cSystem.Object%2cSystem.Collections.IComparer)): it needs to "parse" the C# expressions so that it can separately hyperlink the return type and parameter types in a method. (Compare [to MSDN](https://docs.microsoft.com/en-us/dotnet/api/System.Array.BinarySearch?view=netframework-4.7#System_Array_BinarySearch_System_Array_System_Object_System_Collections_IComparer_) which *doesn't* hyperlink parameter types in the same manner.)

Additionally, I'm rather fond of the [*older* MSDN declarations](https://msdn.microsoft.com/en-us/library/8k7w8xwf(v=vs.110).aspx) which would place each parameter on a new line:

    public static int BinarySearch(
        Array array,
        object value,
        Comparer comparer
    );

In my ideal world, `//MemberSignature/@Value` could be used "as-is" to generate the HTML in all it's hyperlinked glory, *without* needing byzantine C#-in-XSLT parsers, and with a parameter per line. `//MemberSignature/@Value` doesn't readily support this, because XML normalizes all whitespace within attribute values, so an explicit newline would become a space...

**Comment by joelmartinez** [comment]
@dend can you give me a bit of background on this request? ie. is it a breaking issue for anyone, or just preference? 

I agree with @jonpryor that the fact that this is a string generated by `mdoc` doesn't give us a whole lot of flexibility in rendering the signature in the first place. I wonder if perhaps there shouldn't be a function in `monodoc.dll`, that given the XML member node, will return an `EcmaDesc` with all the relevant details. This way, the client can easily render all the links, in whatever format is desired?

**Comment by joelmartinez** [comment]
I'm going to close this issue as it hasn't come up again in a long while. I'm assuming that it was initially identified due to the diff during the msdn migration project ... but now that we've cut over to the new API browser, it's presumably not an issue anymore?

Please let me know if we should revisit this discussion :)
