### ISSUE TITLE
[mdoc] Allow exclusion of certain entities from reflection

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#77]
Certain products, such as SQL and Bot Framework, have APIs that ship in the package, but don't need to be documented. In Frameworks Mode, since we already have a configuration file, would be great to have an `exclude` list, where it's possible to specify a list of DocIDs, for which `mdoc` will ignore the entity and all its children and not include them in the output content.

**Comment by joelmartinez** [comment]
I've always considered this problem as simply a "display issue". So instead of maintaining an exclusion list, I've considered adding an `@Exclude` attribute added to the XSD, which could be applied to `/Type`, and `/Member`.  This lets the XML continue to reflect the true shape of the API (even if for one reason or another, the API remains undocumented, or otherwise out of reach for consumers of the library).

In the mdoc world, this would tell `mdoc assemble` to simply avoid bundling those types/members into the final package. Other pipelines that don't go through the `assemble` command would simply take the same into account.

I'm not necessarily _against_ adding an exclude list ... I just don't like it very much, conceptually :) thoughts?

**Comment by joelmartinez** [comment]
See: https://github.com/mono/api-doc-tools/pull/25

**Comment by dend** [comment]
Closing this issue - agree that all-up, this is a display issue, and for docs.microsoft.com, we already implemented a filter mechanism that can tackle this problem.
