### ISSUE TITLE
[mdoc] Support NuGet information in ECMAXML

### ISSUE THREAD

**Issue by dend** [mono/api-doc-tools#80]
Add a node that identifies that a certain API entity is sourced from a NuGet package.

**Comment by joelmartinez** [comment]
@dend can you give me an example of what information this node might include? nuget id? what about nugets that are only available via private nuget feeds?

**Comment by dend** [comment]
@joelmartinez on our side, we can maintain any number of NuGet feeds - I think this should be abstracted out from the framework file. We would need to specify two items:

* Package ID
* Package version

Everything else should be resolved by the CI job that will be reading this in.

**Comment by katebialiatka** [comment]
Hello,
I have some questions in regards to this issue. Could you please comment on them?

1. What would be a final decision - do we want to close this ticket since work will be done with issue #81? If not, question are the same like for #81

2. What would be the parent xml element to put `<nugetInfo>` tag inside?

**Comment by dend** [comment]
Per conversation with @joelmartinez, we should probably close this in favor of #81

**Comment by joelmartinez** [comment]
thanks :)
