### ISSUE TITLE
Explicit Interface Implementation properties and indexers have wrong name

### ISSUE THREAD

**Issue by TianqiZhang** [mono/api-doc-tools#92]
We found that if a member is EII (Explicit Interface Implementation), and if it's a Property or Indexer, its name will have an extra interface name in it, which is wrong. For example class `Microsoft.VisualBasic.Collection` has an member that implements `System.Collections.IList.IsFixedSize`, however in mdoc generated ECMAXML its name is:
`<Member MemberName="System.Collections.IList.IListIsFixedSize">`, note **IList**IsFixedSize has extra **IList** prefix.

**Comment by joelmartinez** [comment]
As mentioned here, mdoc needs to change how it handles explicitly implemented members, https://github.com/mono/api-doc-tools/issues/51#issuecomment-290751321

Since the actual member name can be anything (ie. this can be user provided in vb.net), we need to switch to a more standardized handling of EII ... which is to say that we'll simply write the membername based on the provided implementation metadata, rather than the name.

**Comment by katebialiatka** [comment]
@joelmartinez 
During the investigation, it appears that `IListIsFixedSize` is the name of the property which developer gave to the specific implementation of the property from the interface (in VB, it is possible to name implementation in a different way from the name in the declaration).

To insert the name of the property `PropertyDefinition.Name` to the XML is used. And since it contains a user-defined name, there is some ambiguity in the docs.

**So the question is**:  what is the aim of documenting - state the name of the initial property or state a value which developer provides?

P.S. It is possible to see the name of the initial property by examining next item `PropertyDefinition.GetMethod.Overrides`.

**Comment by joelmartinez** [comment]
@katebialiatka You're right that this is a delicate issue, in which we have to be really certain of what direction we decide to go in. I think @terrajobst put it best here in [this comment](https://github.com/mono/api-doc-tools/issues/51#issuecomment-308176193) when he said:

> technically explicitly interface implementations are private methods, so the name is arbitrary and the compiler could choose any name. What matters is that the type's vtable is guaranteed to have a mapping for that interface method; **there simply isn't a public API that can be called** without going through interface dispatch.
> 
> The fact that our documentation tools use the private methods as the thing to hang of the docs for explicitly implemented interface methods is a design choice of our tools.

Emphasis mine; as a general rule, mdoc documents _public APIs_. So as he mentions, there's no way to actually call this method using the private/adhoc name given to it in VB, so we should document it using the form that _can_ be called by other code; this also matches the behavior of C# does by default.

So a few other things to consider:

- Not sure if this is necessary, but consider adding a new value to the member node to track the `ExplicitInterfaceName` (if it differs from the member name we get from the metadata reflection). If you decide to add this, make sure you modify the XSD accordingly.
- We have to make sure that the docids that we generate, match the docIDs that both mono.cecil, and the compiler's `/doc` flag generates. 
    - You will probably want to have some VB examples to work from so that you can have an example to test against
    - Remember that if you can't get this to compile on mono (I'm honestly not sure the status of [mono's VB.NET support](http://www.mono-project.com/docs/about-mono/languages/visualbasic/) ... just compile on windows, and check in the assemblies like you did with c++ test assemblies.
    - Make sure that the importer works ... you can [see an example](https://github.com/mono/api-doc-tools/blob/master/mdoc/Makefile#L405) of an integration test that imports from a docxml (mdoc uses the name "slashdoc" internally).
- In a [previous implementation](https://github.com/mono/api-doc-tools/pull/47/files#diff-7eb09bf267acf8baf599c5a2ec2c7a7eR3727), I went to great lengths to work around this issue by using some naming conventions commonly used in some BCL VB libraries ... this code will probably have to be reviewed, and changed or removed.
- The [`SlashDocMemberFormatter`](https://github.com/mono/api-doc-tools/blob/8f37b81f6e4847ebabd71b850e872ea5b8db58f2/mdoc/Mono.Documentation/MDocUpdater.cs#L2383) is used to generate what are essentially docIDs. You should verify that any changes you make will not cause any regressions in how this formatter is used.
- You will need to make sure that the `DocumentationEnumerator` and `EcmaDocumentationEnumerator` classes are equipped to handle this change in how we're naming things ... it needs to be able to [match](https://github.com/mono/api-doc-tools/blob/8f37b81f6e4847ebabd71b850e872ea5b8db58f2/mdoc/Mono.Documentation/Updater/DocumentationEnumerator.cs#L43) the reflected member, with the XML node, given its name.
- Related to the prior point, this code needs to be able to _migrate_ existing EcmaXML repositories, that may or may not be using the "old" name ... because if it doesn't match the existing nodes to the right member, it will probably end up deleting the existing node (along with documentation), and just making a new/blank one.

And lastly; @dend, can you check to see if this change will affect any downstream elements of the pipeline? from the front-end, to the intellisense generation?

**Comment by dend** [comment]
I am with @joelmartinez on this one - the name we want is the name that is universally used within the CLR, rather than the VB-specific implementation. I don't foresee any issues with that downstream, but adding @mairaw to confirm.

cc: @terrajobst
